### ISSUE TITLE
Updating ctypes locally

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#100]
- Occasionally, some python packages uses `find_library` and `CDLL` to find and load a library, it fails unless one use `LD_LIBRARY_PATH` which we avoid.
- On Unix, [`find_library`](https://github.com/python/cpython/blob/db3ff76da19004f266b62e98a81bdfd322861436/Lib/ctypes/util.py#L327) returns the SO name, not the full path as on MacOS

Reference issue : https://bugs.python.org/issue21042

Our module could be patched, since only on Unix it does return the SO name and not the full path.
The code still find the full path but returns only the name.

---

To reproduce:
```
>>> from ctypes.util import find_library
>>> from ctypes import CDLL
>>> import os
>>> find_library('mpi')
'libmpi.so.40'
>>> CDLL(find_library('mpi'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpi.so.40: cannot open shared object file: No such file or directory
>>> CDLL(os.path.join(os.environ['EBROOTOPENMPI'], 'lib', find_library('mpi')))
<CDLL '/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/libmpi.so.40', handle 22ac8b0 at 0x2b5b289c73d0>
>>> 

```

**Comment by mboisson** [comment]
Is there a mechanism by which we could we shadow `ctypes.util`'s `find_library` by our own version, without necessarily patching existing installations ?

**Comment by bartoldeman** [comment]
it's actually interesting that `find_library` manages to find the absolute path name already but then doesn't use it:
it uses the equivalent of
```
$ gcc -Wl,-t -o /dev/null -lmpi 2>&1 | grep '[^\(\)\s]*libmpi\.[^\(\)\s]*'
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so
```

**Comment by mboisson** [comment]
We probably need to be careful how we do it, but : 
```
find /home/mboisson/test_overwrite_ctypes/
/home/mboisson/test_overwrite_ctypes/
/home/mboisson/test_overwrite_ctypes/ctypes
/home/mboisson/test_overwrite_ctypes/ctypes/__init__.py
/home/mboisson/test_overwrite_ctypes/ctypes/util.py
``` 

and then 
```
export PYTHONPATH=$HOME/test_overwrite_ctypes:$PYTHONPATH
``` 

will make it pick up that local version.

**Comment by mboisson** [comment]
My rationale for wanting to use a local customization like that is that if it backfires, it can easily be withdrawn.

**Comment by mboisson** [comment]
Using this local override, on Linux, `_findLib_gcc` is called, and returns the absolute path to the `.so`. However, this is then passed through to `_get_soname`, which calls `objdump` and parses it with a regex to find `SONAME`: 

i.e., `_findLib_gcc` returns `/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so` 
and `_get_soname` does the equivalent of: 
```
objdump -p -j .dynamic /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so | grep SONAME
objdump: section « .dynamic » mentionnée dans une option -j n'a été trouvée dans aucun fichier d'entrée
  SONAME               libmpi.so.40
``` 

and returns `libmpi.so.40`

**Comment by mboisson** [comment]
I created this repository to attempt to tackle this issue. https://github.com/ComputeCanada/custom_ctypes

**Comment by mboisson** [comment]
This commit is what needs to be done: 
https://github.com/ComputeCanada/custom_ctypes/commit/b3a0288f6e6174b502107a92ac8cd0db0842411b

Then, it is a matter of shadowing Python's built-in `ctypes`. Seems to work with `PYTHONPATH`, i.e. something like
```
PYTHONPATH=$HOME/git/custom_ctypes/lib/python${EBVERSIONPYTHON::3}/site-packages
``` 

but not with `EBPYTHONPREFIXES`

**Comment by ccoulombe** [comment]
Users often fiddle with `PYTHONPATH` so this is brittle.

**Comment by mboisson** [comment]
not responsible for users breaking their environment ;) 

Jokes aside, we can probably make it work with our `sitecustomize.py`, maybe a `EBPYTHONPREFIXES_PRIORITY` which would take precedence over `python`'s core libraries.

**Comment by mboisson** [comment]
@bartoldeman might know how to do that

**Comment by mboisson** [comment]
With the above PR and the `custom_ctypes` checked out in my home, defining: 
```
# to get the modified ctypes
export EBPYTHONPREFIXES_PRIORITY=$HOME/git/custom_ctypes

$ for v in 2.7 3.6 3.7 3.8 3.9; do module load python/$v; PYTHONPATH=$HOME/git/easybuild-computecanada-config/python/site-packages:$PYTHONPATH python -c "from ctypes.util import find_library; from ctypes import CDLL; import os; print(find_library('mpi')); CDLL(find_library('mpi'));"; done

Les modules suivants ont été rechargés avec un changement de version :
  1) python/3.9.6 => python/2.7.18

/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40

Les modules suivants ont été rechargés avec un changement de version :
  1) python/2.7.18 => python/3.6.10

/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40

Les modules suivants ont été rechargés avec un changement de version :
  1) python/3.6.10 => python/3.7.9

/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40

Les modules suivants ont été rechargés avec un changement de version :
  1) python/3.7.9 => python/3.8.10

/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40

Les modules suivants ont été rechargés avec un changement de version :
  1) python/3.8.10 => python/3.9.6

/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40
```

**Comment by ccoulombe** [comment]
We might want to have some reminder to remove those overwrite if the issue gets fixed upstream. Or to add the one shadowing file when we deploy a newer python module.

**Comment by mboisson** [comment]
PR https://github.com/ComputeCanada/software-stack-custom/pull/28 will allow our own `sitecustomize.py` to stay ahead of EasyBuild's version even when loading python modules.

**Comment by mboisson** [comment]
The above PR won't work, because it is not the correct path to find our `sitecustomize.py`. The correct path is being added in our `python` modules. Either we need to reinstall our python modules or we need to update our `gentoo` module to include the correct path. Any preference ?

**Comment by mboisson** [comment]
This is now fixed on build-node with the installation of this module: 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/c/custom-ctypes/custom-ctypes-1.1.eb
supported by this `sitecustomize.py`: 
https://github.com/ComputeCanada/easybuild-computecanada-config/blob/main/python/site-packages/sitecustomize.py#L44

and disabling upstreams' `ebpythonprefixes` support: 


Will push the changes next week.

**Comment by mboisson** [comment]
This is now deployed in production: 
```
[mboisson@narval2 ~]$ module load python custom-ctypes
[mboisson@narval2 ~]$ python -c "from ctypes.util import find_library; from ctypes import CDLL; import os; print(find_library('mpi')); CDLL(find_library('mpi'));"
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/intel2020/openmpi/4.0.3/lib/../lib64/libmpi.so.40
```
