### ISSUE TITLE
Enable Lmod cache

### ISSUE THREAD

**Issue by rptaylor** [ComputeCanada/software-stack#106]
https://lmod.readthedocs.io/en/latest/130_spider_cache.html

Might be useful, perhaps doable with gateway publishing.

**Comment by mboisson** [comment]
This looks like it is a build-time setting, and is a single cache

**Comment by mboisson** [comment]
Lmod cache can now be tested on build-node by doing 
```
export RSNT_ENABLE_LMOD_CACHE=yes
module update
``` 

In order to regenerate the cache, one must run the above, and then run
```
 $LMOD_DIR/update_lmod_system_cache_files /cvmfs/soft.computecanada.ca/custom/modules
``` 

for all combinations of `RSNT_CPU_VENDOR_ID={amd,intel}` and `RSNT_ARCH={sse3,avx,avx2,avx512}`

**Comment by mboisson** [comment]
Similarly as for `generate_mii_index.py`, we now have a script to generate the Lmod caches here
https://git.computecanada.ca/rsnt-software/rsnt-scripts/-/blob/master/etc/rsnt/generate_lmod_cache.py

**Comment by mboisson** [comment]
The Lmod cache can now be enabled on clusters by running 
```
export RSNT_ENABLE_LMOD_CACHE=yes
module update
```

**Comment by mboisson** [comment]
This is now enabled by default.
