### ISSUE TITLE
Data installation under /cvmfs/data.rsnt.computecanada.ca

### ISSUE THREAD

**Issue by alikerr** [ComputeCanada/software-stack#108]
When installing data using the option --installpath-software=/cvmfs/data.rsnt.computecanada.ca/content/easybuild/data/, eb does not add the year branch automatically. So, the option to use is {probably} "/cvmfs/data.rsnt.computecanada.ca/content/easybuild/data/2020" instead of /cvmfs/data.rsnt.computecanada.ca/content/easybuild/data/"

**Comment by mboisson** [comment]
This is now fixed.
