### ISSUE TITLE
is it possible to combine "rstudio-server/2021.09.1+372" with different R versions?

### ISSUE THREAD

**Issue by pescobar** [ComputeCanada/software-stack#111]
Hi,

I am doing some testing combining the ComputeCanada software stack with [Open OnDemand](https://openondemand.org/) to provide jupyterlab and Rstudio in a cloud environment. 

When I test `rstudio-server/2021.09.1+372` + `r/4.1.2`  it works fine.

If I try to launch Rstudio with an older R version it doesn't work. e.g. if I load `rstudio-server/2021.09.1+372` + `r/4.1.0` the R version returned by `sessionInfo()` in Rstudio is still `r/4.1.2`. 

When I try `rstudio-server/2021.09.1+372` + `r/4.0.5`  the Rstudio rsession startup crashes with error message `unable to initialize the JIT` and I get the error in the screenshot when trying to connect with the browser

![Screenshot from 2022-06-21 10-14-26](https://user-images.githubusercontent.com/103797/174762258-356d7e49-dd07-4109-9832-9c405496cdc1.png)

I have noticed that the [rstudio easyconfig](https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/r/RStudio-Server/RStudio-Server-2021.09.1%2B372-gcccoreflexiblas-2020a.eb#L26) has `r/4.1.2` as build dependency and some of the rstudio binaries are linked with the `r/4.1.2` libraries e.g.

```bash
$> ldd /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/rstudio-server/2021.09.1+372/bin/rsession |grep -i 4.1.2
        libR.so => /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/r/4.1.2/lib/R/lib/libR.so (0x00007f03384f0000)
```

Is it possible to combine `rstudio-server/2021.09.1+372` with different R versions? Or it can only be used with `r/4.1.2`? 

Thanks for any help or advice.

**Comment by ccoulombe** [comment]
We've added corresponding `rstudio-server` matching the R version :
```
rstudio-server/4.1 # with r/4.1
rstudio-server/4.2 # with r/4.2
rstudio-server/4.3 # with r/4.3
```
ref: [caa9b8ae600d96b3e969382172337f83d91a19ad](https://github.com/ComputeCanada/easybuild-easyconfigs/commit/caa9b8ae600d96b3e969382172337f83d91a19ad)
