### ISSUE TITLE
Supporting the building and deployment of containers

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#116]
- [x] Create a CCDB group for access control
- [x] Create a GitHub team for access control
- [x] Create a repository to host recipes
- [x] Write documentation
- [x] Configure publisher node to allow publishing of containers (new repository)
- [ ] ~Configure VM for building images that requires Docker (separate VM, with special software)~ (no need, we use podman)

**Comment by rptaylor** [comment]
Buildah (and podman if needed) should be able to do anything that Docker can do, except they are fully unprivileged and do not entail sudo privileges for users.  If they can be used instead of Docker it could remove the need for a separate VM for image building, unless other special software is required.

**Comment by mboisson** [comment]
What's the relation to #56 ?

**Comment by rptaylor** [comment]
#56 is the automated publishing system (a file managed in git defines which OCI/Docker images on an external registry to convert to Apptainer/Singularity and publish to CVMFS).

This is for manual publishing of images, what I understood from Tannistha is that the source images are built with Apptainer/Singularity, not Docker/buildah.

However both systems will publish images to the same repo. To avoid interference between the two publishing mechanisms, the manually published images will be kept within a specific subdirectory such as /store.  That means the transaction command will be  `cvmfs_server transaction reponame/store`

**Comment by mboisson** [comment]
Tagging @BioBP

**Comment by mboisson** [comment]
Repository to host container recipes: https://github.com/ComputeCanada/containers-recipes

**Comment by mboisson** [comment]
This is now done.
