### ISSUE TITLE
Running jupyter lab in my own virtual environment - Permission error in tutorial

### ISSUE THREAD

**Issue by AngCamp** [ComputeCanada/software-stack#133]
I need to run a notebook in an environment which uses a custom data loading python module, this is the module [here](https://allensdk.readthedocs.io/en/latest/_static/examples/nb/visual_behavior_neuropixels_data_access.html) .   I am following the jupyterlab tutorial for compute canada clusters [here](https://docs.alliancecan.ca/wiki/Advanced_Jupyter_configuration)

But when I try to run this line 

`echo -e '#!/bin/bash\nunset XDG_RUNTIME_DIR\njupyter lab --ip $(hostname -f) --no-browser' > $allensdkenv/bin/jupyterlab.sh
`

I get the following error...

```
(allensdkenv) (base) [angcamp@cdr2688 angcamp]$ echo -e '#!/bin/bash\nunset XDG_RUNTIME_DIR\njupyter lab --ip $(cdr2688 -f) --no-browser' > $allensdkenv/bin/jupyterlab.sh
bash: /bin/jupyterlab.sh: Permission denied
```

I think my hostname may be wrong but also this permission error is unexpected, how can I run a jupyternotebook in an environment I create myself?

**Comment by ccoulombe** [comment]
@AngCamp Please write to support instead : https://docs.alliancecan.ca/wiki/Technical_support
You can also use one of the already available hub on the systems.
You must change the executable bit on your file as done in the previous step.

**Comment by AngCamp** [comment]
I'm not sure if this exists for virtualenv but there is this option for conda which adds a widget to the notebook which allows a user to select which environment to run a notebook in: https://medium.com/@jy.wong.xeron/managing-jupyter-notebooks-and-conda-environments-6b8c627e0c2f#3fa3

This is for conda which I know is frowned upon by compute canada but just as a suggestion there may be alternative solutions.

**Comment by ccoulombe** [comment]
@AngCamp If you encounter any issues, please write to support.
Conda is indeed an humonguous issue on the systems. In all cases, you can do the same thing in a standard python virtual environment.

**Comment by AngCamp** [comment]
But the tutorial you have provided to do this is not workking.

**Comment by mboisson** [comment]
Please report support questions to our technical support so that one of our support team can help https://docs.alliancecan.ca/wiki/Technical_support

**Comment by AngCamp** [comment]
Why not just answer on github?  It's easier to share code and it's more convenient than using an email thread.

**Comment by mboisson** [comment]
All of our support requests need to go through our standard channel for Technical support.
