### ISSUE TITLE
Update EB hooks - raise error when use_pip is not used

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#138]
To accompany https://github.com/ComputeCanada/software-stack/issues/137, and prevent future _oopsies_, we need to raise an error if a module has a Python extension and uses `python setup.py install` and not `pip install`.

We then need to update the recipe to use: 
```
        'use_pip': True,
        'use_pip_for_deps': True,
        'sanity_pip_check': True,
```
and fix/update any issues with the installed python packages.

**Comment by mboisson** [comment]
I suggest setting
```
exts_default_options['use_pip'] = True
exts_default_options['use_pip_for_deps'] = True
exts_default_options['sanity_pip_check'] = True
``` 

if there are Python extensions

**Comment by mboisson** [comment]
Or maybe add a sanity check that there are no `.egg` files in the install dir ? 

Testing for use_pip in all extensions is not trivial.

**Comment by ccoulombe** [comment]
I'd prefer to raise an error (like we do with CMake). Plus, these will be defaults in the next EB version

**Comment by mboisson** [comment]
> Plus, these will be defaults in the next EB version
which won't raise an error
