### ISSUE TITLE
libgd on gentoo/2023 does not support GD images

### ISSUE THREAD

**Issue by aroudgar** [ComputeCanada/software-stack#140]
libgd-2.3.3 installed  on gentoo/2023 does not support GD images and the reason is that in  "libgd >= 2.3.3"  we need to explicitly specify  "--enable-gd-formats" option in configure command otherwise it is disabled by default while for libgd<2.3.3 this option is enabled by default. I tried to make a module for this version with this option using easybuild  but I get an error message indicating that  libgd software is filtered.

**Comment by bartoldeman** [comment]
This is fixed now, ref: https://github.com/ComputeCanada/gentoo-overlay/commit/78ee6fc3b76b613b932e835111d28a40de6ae897
