### ISSUE TITLE
python3.8 abi nomenclature change

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#15]
With Python 3.8, the abi m flag became useless and was removed but this complicate things with multi_deps . python/cpython@7efc526

For instance, for `configopts` one cannot generically use
```
-DPYTHON3_INCLUDE_DIR=$EBROOTPYTHON/include/python%(pyshortver)sm"
```
It works for python versions under 3.8, but removing the m obviously breaks inferior versions.

This was also brought at the Easybuild level : https://github.com/easybuilders/easybuild-framework/issues/3318

In the meeting, the discussed proposals are :

- add a symlink for include/python3.8m -> include/python3.8 (both Gentoo and Nix)
- replace : `prepend_path("CPATH","/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/include")`
with : 
`prepend_path("CPATH","/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/include:/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/include/python3.8")`

**Comment by mboisson** [comment]
@ccoulombe, are you able to use the workarounds proposed in https://github.com/easybuilders/easybuild-framework/issues/3318 for now, until this is implemented in upstream easybuild ?

**Comment by ccoulombe** [comment]
Yes I can. The following works with `multi_deps`:
```
"-DPYTHON3_INCLUDE_DIR=$EBROOTPYTHON/include/python%(pyshortver)s$(python3-config --abiflags)",
```
But one has still to adjust the sanity checks.

I'd still prefer a symlink so it works _transparently_ for everyone.

**Comment by mboisson** [comment]
Ok. Then I will close this issue in our repository. The more general issue can be addressed in upstream EasyBuild.
