### ISSUE TITLE
Support Numpy 2.0

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#155]
Roadmap to support and deploy Numpy 2.0

- [x] Build Numpy `2.1.1` wheels
- [x] Test builds with numpy (with 1.x ABI compat, and not)
- [x] #156
- [x] #154 
- [x] Deploy patched 2023 wheels
- [x] Build pandas, scipy and matplotlib compatible wheels
- [x] Deploy numpy, pandas, etc. wheels for 2023
- [x] #161
- [x] #160
- [x] #157
- [x] #158
- [x] #159
- [x] Add troubleshooting issue to Trouble Shooting section on Python page

By adding numpy 2.0, we risk of : 

1. breaking modules whichs used `oldest-supported-numpy` and uses a `scipy-stack` for its `numpy`
2. breaking of users environment where they install any version of numpy and use `scipy-stack` (or any module that uses it, eg `arrow` or `opencv`).
3. breaking current wheels that were built with 1.x and not constrained to `numpy<2.0`
4. breaking current jobs of users that do not specify versions or use a requirements file

**Comment by ccoulombe** [comment]
#### Numpy 2.1.1 + matplotlib 3.9.1 (built with oldest-supported-numpy), no 1.x compat
```python
>>> import matplotlib

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
....
AttributeError: _ARRAY_API not found
ImportError: numpy.core.multiarray failed to import
```

#### Numpy 2.1.1 + matplotlib 3.9.2 (built with numpy 2.1.1), 1.x compat
```python
(32603) [coulombc@node2 wheels_builder]$ pip install numpy==1.26.4 matplotlib-3.9.2+computecanada-cp311-cp311-linux_x86_64.whl 
(32603) [coulombc@node2 wheels_builder]$ python -c 'import matplotlib'
(32603) [coulombc@node2 wheels_builder]$ 
```

**Comment by mboisson** [comment]
Cool, au moins numpy donne une erreur compréhensible à l'usager.

**Comment by ccoulombe** [comment]
numpy 2.1.1 and the wheelhouse are now synced to the systems.
