### ISSUE TITLE
Patch modules that depends on any `scipy-stack`

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#157]
Patch modules that depends on any `scipy-stack` to avoid clash with the newer `scipy-stack`. 
Specify `<2024b` or something like that

- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-16.1.0-gcccorecuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-15.0.1.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-14.0.1.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-16.1.0.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-15.0.1-gcccorecuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-14.0.1-gcccorecuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-17.0.0-gcccorecuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-14.0.0.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-14.0.0-gcccorecuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/Arrow/Arrow-17.0.0.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/MuJoCo/MuJoCo-3.1.6.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/MuJoCo/MuJoCo-3.0.1.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/ESMF/ESMF-8.6.0-gofb-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenMM/OpenMM-8.1.1-gofbc-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenMM/OpenMM-8.1.1-gofb-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenMM/OpenMM-8.0.0-gofbc-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenMM/OpenMM-8.0.0-gofb-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenCV/OpenCV-4.10.0-gccflexiblascuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenCV/OpenCV-4.10.0-gccflexiblas-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenCV/OpenCV-4.9.0-gccflexiblas-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenCV/OpenCV-4.8.1-gccflexiblascuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenCV/OpenCV-4.8.1-gccflexiblas-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/RDKit/RDKit-2023.09.3-GCC-12.3.0.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/RDKit/RDKit-2024.03.4-GCC-12.3.0.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/OpenMC/OpenMC-0.15.0-gompi-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/faiss/faiss-1.7.4-gccflexiblascuda-2023a.eb
- [x] /cvmfs/soft.computecanada.ca/easybuild/ebfiles_repo/2023/faiss/faiss-1.8.0-gccflexiblascuda-2023a.eb

**Comment by mboisson** [comment]
```
depends_on('scipy-stack')
```
should become 
```
if convertToCanonical(LmodVersion()) >= convertToCanonical("8.2.9") then
  depends_on(between("scipy-stack",'2023b<','<2024b'))
end
```

**Comment by mboisson** [comment]
This is now done and all modules are deployed.
