### ISSUE TITLE
Update rstudio-server module to support latest R 4.4

### ISSUE THREAD

**Issue by pescobar** [ComputeCanada/software-stack#162]
It would be great if you add a new module for latest R release. 

- R version 4.4.0 was released on 2024-04-24. 
- R version 4.4.1 was released on 2024-06-14

Currently the software stack provides these three Rstudio modules

```
rstudio-server/4.1
rstudio-server/4.2
rstudio-server/4.3
```

Thanks for your work. Your software stack is really useful for us.

**Comment by ccoulombe** [comment]
@pescobar Yes, we will add a Rstudio-server with R 4.4

**Comment by pescobar** [comment]
thank you!

**Comment by ccoulombe** [comment]
@pescobar RStudio-Server 4.4 is now (or will be in a few minutes) available. Cheers!
