### ISSUE TITLE
qt/6.5.3 module missing/incorrect RPATH

### ISSUE THREAD

**Issue by stuart-cls** [ComputeCanada/software-stack#163]
With the following modules on a node:

```
module load StdEnv/2023
module load qt/6.5.3
module load scipy-stack  #this loads python/3.11.5
```

running a test application (over X11 forwarding) 

```test_pyqt6.py
import sys
from PySide6.QtWidgets import QApplication, QLabel

app = QApplication(sys.argv)
label = QLabel("Hello World!")
label.show()
app.exec()
```

results in an error due to a missing library `libQt6XcbQpa.so.6`. 

We have not yet determined the package responsible. 

Workaround is 
```
export LD_LIBRARY_PATH=/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/qt/6.5.3/lib
```

**Comment by mboisson** [comment]
Can you reproduce if you load the `custom-ctypes` module ?

**Comment by stuart-cls** [comment]
Yes, loading `custom-ctypes/1.2` does not change the error / error message.

The exact error is:
```
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, vkkhrdisplay, minimalegl, xcb, eglfs, offscreen, minimal, vnc.

Aborted (core dumped)
```

However my colleague Robert Wagner found that this error message is misleading and always reports the problem is with the cursor library: https://github.com/zeroepoch/plotbitrate/commit/59a12abca5673a73dc2826e3ddeb95f78c63b9c1. From that he found the missing library was in fact `libQtXcbQpa.so.6`

**Comment by bartoldeman** [comment]
This is fixed now (by adding an RPATH entry of `$ORIGIN/../../lib` to `$EBROOTQT6/plugins/platforms/libqxcb.so`)
