### ISSUE TITLE
Software in Gentoo that could be only in modules

### ISSUE THREAD

**Issue by bartoldeman** [ComputeCanada/software-stack#22]
The following software packages are installed in both Nix and Gentoo but also have modules:
```
(*) multiple module versions installed
snappy *
lmdb
mysql
postgresql *
xerces-c++ *
tktable
git-annex
ffmpeg
zeromq
cfitsio *
proj *
gnuplot *
```
we should decide which of these should be removed from the Gentoo prefix.
For Nix that would be too risky as we could be breaking user jobs.

**Comment by bartoldeman** [comment]
Should discuss with various people for their reasons to install them as modules:
@ostueker : ffmpeg
@alikerr : lmdb, tktable, gnuplot
@mboisson : mysql, postgresql, git-annex, zeromq, proj, xerces-c++ (xerces-c++ originally Masao and Rob, no longer with us)
@bmoa : snappy, cfitsio

For scientifically oriented packages such (cfitsio, proj, gnuplot) it makes sense to use modules.
For databases (lmdb, mysql, postgresql) probably be too (multiple versions for postgresql)
I'm not sure about the others, in particular git-annex. With EB it's installed as a binary, with Gentoo it's compiled from source but the builddependency list is huge (uses GNU Haskell)

**Comment by mboisson** [comment]
git-annex: this was installed in EasyBuild mostly because it did not compile easily in Nix

**Comment by mboisson** [comment]
protobuf needs to be remove from gentoo

**Comment by preney** [comment]
I agree with Bart's comment. That said, for databases in Gentoo, be aware that PostgreSQL is slotted (9.4, 9.5, 9.5, 10, 11, 12, 13) so those (major) versions can coexist --the servers just need to run on different port numbers (if running on the same machine) if such is desired. (I looked to see how many: git-annex has 84 direct dependencies when built from source in Gentoo.)

**Comment by bartoldeman** [comment]
I deleted mysql, postgresql, lmdb, cfitsio, gnuplot, proj from the Gentoo Prefix now.
I also removed protobuf, however, mosh depends on that and I removed mosh too (as most (all?) clusters don't allow connecting via mosh anyway).

**Comment by ostueker** [comment]
>
> Should discuss with various people for their reasons to install them as
> modules:
> @ostueker <https://github.com/ostueker> : ffmpeg
>

In case of ffmpeg the reason was that a user wanted/needed a newer version
than what was available in NIX.

I’ve just turned off my PC but there might be some info in the OTRS ticket
why I decided against updating the version in NIX.

-- 
Oliver Stueker, Dr. rer. nat. -            Research Consultant
Memorial University of Newfoundland - ACENET -  Compute Canada
Email: support@computecanada.ca             support@ace-net.ca
Web:   http://www.ace-net.ca     https://docs.computecanada.ca
Phone: +1 (709) 864-3021                        Office: HH2033
A Compute Canada Regional Partner

**Comment by mboisson** [comment]
If this is done, we can close this issue ?

**Comment by bartoldeman** [comment]
We still have ffmpeg in Gentoo. Let me look into that later.

**Comment by bartoldeman** [comment]
I've started removing ffmpeg, slurm-pmi and git-annex, and the 60 Haskell packages. Will check a little more about ghc.

**Comment by bartoldeman** [comment]
we have another Haskell user in Gentoo: darcs, though I am not sure who uses that these days.

**Comment by bartoldeman** [comment]
And yet another big Haskell user is `pandoc`. I decided to just keep that (and `darcs`). Both have been mentioned in user tickets in the past.

Removal of the others complete and pushed to production.
