### ISSUE TITLE
Dynamically hidding/showing cuda versions based on installed cuda libraries

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#25]
Clusters do not upgrade NVidia drivers at the same time. Having cuda modules being hidden or shown, dynamically, based on the installed cuda drivers, would be useful

**Comment by mboisson** [comment]
Implemented in commit 
https://github.com/ComputeCanada/software-stack-config/commit/9728933b2bc71fbdd783c35d3cdf51bc841de568

I would like a review of this change @bartoldeman or @ccoulombe

**Comment by ofisette** [comment]
On non CC-cluster machines, `/usr/lib64/nvidia` does not exist. Therefore, there should be a check for that directory at the start of auto-detection. Otherwise, the following error happens:

```
$ module spider cuda
/cvmfs/soft.computecanada.ca/custom/software/lua/bin/lua: ...a/software-stack-config/lmod/SitePackage_visible.lua:3: cannot open /usr/lib64/nvidia: No such file or directory
[...]
```

The best is probably to hide all CUDA modules if the directory is non-existent, since the CC CUDA toolkits rely on the drivers being available in that directory.

I also suggest that some advance warning be given before deployment since not all RSNT sites have CUDA drivers installed on login nodes. On our local cluster at USask, for instance, drivers are only installed on the GPU-equipped compute nodes. Other sites may need time to make the change too.

**Comment by mboisson** [comment]
Commit https://github.com/ComputeCanada/software-stack-config/commit/64494ffb6dc1fd8c722ff15749c1be6d67ba25d9 does an early abort if `/usr/lib64/nvidia` is not present, and it just hides all `cuda` modules. Can you test it to see if it fixes the crash ?

**Comment by mboisson** [comment]
@ofisette confirmed that it fixes the crash (and hides all of the `cuda` modules)

**Comment by mboisson** [comment]
There are three options for this feature. We can 
1) Do this only on specific Compute Canada clusters
2) Do this for every client of our CVMFS stack by default, but allow a flag to disable the feature.
3) Do this for every client of our CVMFS stack, and not allow a flag to disable it.  

Any opinion ?  @bartoldeman @ccoulombe

**Comment by ofisette** [comment]
Could we move this check to the initialisation phase of CVMFS and store the detected version in RSNT_CUDA_DRIVER_VERSION (if unset), using 0 as a sentinel value for no CUDA driver? Then, it would be reasonable to run it everywhere, and those who want to bypass it can set the env var explicitly before init. If I understand how module visibility is checked, this would also reduce access to the file system as the drivers would be checked only once.

**Comment by mboisson** [comment]
Good question. In principle, yes, that would be doable. We still want to do it in modules, to be shell-agnostic, but we do something similar for `RSNT_INTERCONNECT`, and `RSNT_ARCH`.

**Comment by bartoldeman** [comment]
yes RSNT_CUDA_DRIVER_VERSION would allow sites to unhide cuda modules on login nodes even if /usr/lib64/nvidia is not installed. Then it's indeed similar to RSNT_INTERCONNECT and RSNT_ARCH, auto-detect by default but respect setting if already set.

**Comment by mboisson** [comment]
Ok, I'll work on making it similar to RSNT_INTERCONNECT.  This also means that we can have a "default version" of 440.33 (if drivers are not found), which is enough to keep visible up to cuda 10.2, and starts hiding only at cuda 11.0

**Comment by ccoulombe** [comment]
Late to the party, but I think it should be CC specific only and avoid using one more env. variable.

**Comment by mboisson** [comment]
@ccoulombe, to be CC-specific, it needs an environment variable regardless. But care to elaborate your rationale ?

**Comment by mboisson** [comment]
For what it's worth, it is already implemented on the build-node, using
https://github.com/ComputeCanada/software-stack-custom/commit/c3ce5841f5a41aa57b9d0ef0f313face6751abf2
and
https://github.com/ComputeCanada/software-stack-config/commit/391019b36a3272ad5fc2909ccf6dcc3d174a3eb3
https://github.com/ComputeCanada/software-stack-config/commit/0279d59bd4f8bc331df720548487935382cda104
https://github.com/ComputeCanada/software-stack-config/commit/536cf123f0cbdfc107597483a399370bbdc30b3f
https://github.com/ComputeCanada/software-stack-config/commit/2d5d734909fa1bdebe2d6a5e602ab46270de7dbb

Note that 
https://github.com/ComputeCanada/software-stack-config/blob/2d5d734909fa1bdebe2d6a5e602ab46270de7dbb/lmod/SitePackage_visible.lua#L80

makes it backward compatible for sites which may not have `/usr/lib64/nvidia` on the login node. It will show up to `cuda/10.2` without modification. If they want `cuda/11.0`, they will have to either ensure they have `/usr/lib64/nvidia` on the login node, or define `RSNT_CUDA_DRIVER_VERSION`

**Comment by ccoulombe** [comment]
Not sure I see why? (but this is the end of a very long day). Only the check is sufficient?
I tend to think that non-cc site using CVMFS should adapt and not the other way around otherwise it will never end in customizations.

**Comment by mboisson** [comment]
The point is actually avoiding breakage for non-CC sites.

**Comment by ofisette** [comment]
I tested the last version on a non-CC site with very heterogeneous hardware and no CUDA drivers on the login nodes. Everything seems to work fine: we can hide/show CUDA versions as desired, backward compatibility is maintained, and the auto-detection feature works for nodes with the drivers.

**Comment by mboisson** [comment]
This is now deployed to the dev repository.

**Comment by mboisson** [comment]
I deployed it to prod now.
