### ISSUE TITLE
IP addresses for CVMFS endpoints

### ISSUE THREAD

**Issue by joeydumont** [ComputeCanada/software-stack#26]
I'd like to use the CC software stack, but my organization is asking me to provide IP addresses for the CVMFS endpoints to whitelist in the firewall.

Are the IPs below correct, and are they subject to change often?

| Domain                             | IP              |
|------------------------------------|-----------------|
| cvmfs-s1-east.computecanada.ca     | 206.167.180.250 |
| cvmfs-s1-beluga.computecanada.ca   | 132.219.136.73  |
| cvmfs-s1-arbutus.computecanada.ca  | 206.12.59.11    |

**Comment by mboisson** [comment]
@rptaylor, can you comment ?

**Comment by rptaylor** [comment]
Those are the current IP addresses , as resolved by DNS.
It is possible but unlikely that they could change.

Accessing stratum 1 servers is equivalent to simply downloading files via HTTP; you only need general internet access.
Normally firewall rules should not be required, except for highly restricted environments that do not even allow outgoing internet connections.

**Comment by joeydumont** [comment]
We are in such an environment, indeed. 

Thanks for the info, I'll go forward with these IPs and make a note of checking IPs if it ever breaks...

**Comment by rptaylor** [comment]
@joeydumont  Be advised that we are now also providing CVMFS repository access via Cloudflare .
The host name is cvmfs-s1.computecanada.net but due to the nature of Anycast it is not associated with any particular IP address.  The list of all IP addresses used by Cloudflare is here: https://www.cloudflare.com/ips/

**Comment by joeydumont** [comment]
Thank you for notifying me, much appreciated!
