### ISSUE TITLE
Determine which way to handle python with the Gentoo stack

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#3]
Gentoo has a peculiar way of handling python version. With the Gentoo stack : 
```
$ module load python/2.7.17; which python; python --version
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python
Python 2.7.17
$ module load python/3.6.9; which python; python --version
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python
Python 3.6.9
$ module load python/3.7.5; which python; python --version
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python
Python 3.7.5
$ module load python/3.8.1; which python; python --version
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python
Python 3.8.1
$ file /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python: symbolic link to python-exec2c
$ file /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python-exec2c
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python-exec2c: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /cvmfs/soft.computecanada.ca/gentoo/2019/lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped
``` 

It seems like to work as expected with `virtualenv`, `pyvenv` and `python -m venv`. 

It selects the version of python based on the environment variable `EPYTHON` : 
```
$ EPYTHON=python3.6 python3 --version
Python 3.6.9
$ EPYTHON=python3.7 python3 --version
Python 3.7.5
$ EPYTHON=python3.8 python3 --version
Python 3.8.1
$ EPYTHON=python2.7 python3 --version
Python 3.7.5
$ EPYTHON=python3.6 python2 --version
Python 2.7.17
``` 

Note that the specific versions still exist : 
```
$ ls  /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python*
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python            /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.6-config   /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.8
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python2           /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.6m         /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.8-config
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python2.7         /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.6m-config  /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3-config
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python2.7-config  /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.7          /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python-config
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python2-config    /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.7-config   /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python-exec2c
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3           /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.7m         /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/pythontex
/cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.6         /cvmfs/soft.computecanada.ca/gentoo/2019/usr/bin/python3.7m-config
``` 

I see no benefit to the user, as the user still needs to load the version of the module that they need in order to get the desired behavior. 

This is however rather confusing, because you always see the same path of python executed from the path. 

There are a few options
1) Install it "a la Gentoo" (i.e. keep it like it is now)
2) Install python through EasyBuild (as we usually do), so that it is based on the path
3) Install python through EasyBuild and hide from users the `python` from Gentoo, to ensure that users load the python module that they need.

**Comment by mboisson** [comment]
@cmd-ntrf could have some insight about this, @ccoulombe as well

**Comment by bartoldeman** [comment]
The Gentoo strategy works to handle different Pythons at the same time but it certainly is different and so can be confusing to users and analysts. The magic is explained here:
https://wiki.gentoo.org/wiki/Project:Python/python-exec

Option 2 is doable, one just need to see what happens when people start mixing EB-built Python 3.7.x with Gentoo Python 3.7.x, because sometimes they might forget to load the python module.

The issue with option 3 is then we need to see what to do with the `python` command by default. If `python` is removed from Gentoo it will fall back to `/usr/bin/python`, which is python 2.7.5 on most clusters. The same issue does not (usually) apply to `pip` and `virtualenv`. Note that Gentoo depends heavily on Python itself, though perhaps not so much the `python` command.

One could also instead add python to StdEnv.

**Comment by mboisson** [comment]
From today's meeting, the path of least surprise seems to be to install Python through EasyBuild. 

Verdict is up on having a wrapper script that would tell users to load a module if they try to use the Gentoo one.

**Comment by preney** [comment]
Option 3 is not possible in practice: it will cause lots of pain. Gentoo's package manager and some other tools are tightly coupled with Python. Removing Python from Gentoo will break (if not right away, then at some point) the Gentoo package manage which is needed to easily maintain the Gentoo subset.

Options 1 or 2 are possible. We probably should have a message for users to module load a Python, or, can we have lmod load a default version of Python? This would auto-hide the Gentoo python and should eliminate this issue.

**Comment by mboisson** [comment]
I should have formulated 3. differently. I did not mean to remove as much as to hide from the users, through a wrapper that has precedence in the PATH.

**Comment by verdurin** [comment]
Personally I prefer option 2, nice and simple.

**Comment by preney** [comment]
The option 2 seems the simplest. Are there any issues with having a default python loaded in the default config for lmod --so that is loaded when they are logged in?

**Comment by mboisson** [comment]
The issue with defaults is always the surprise when we will want to change them in the future. I would rather have no default for python. (other possibly than the default that comes with gentoo, which is our equivalent of the CentOS default without a module loaded).

**Comment by mboisson** [comment]
Further discussion in our meeting on May 8th confirmed the consensus of installing Python through EasyBuild and not through a module wrapped around Gentoo. 

As for the "default" behavior, discussion went around between
1) Keep the Gentoo version visible by default
2) Hide the Gentoo version with a wrapper script that would basically tell the user "you have not loaded a python module, please load one first"
3) Load a python module by default

No clear consensus. Option 1) provides a working, but incomplete python (no virtualenv, pip, etc.). Option 2) provides a "broken" default python, which may or may not be problematic. Option 3) may be challenging in the future if we want to upgrade the default version.

**Comment by mboisson** [comment]
Closing. We installed python modules through EasyBuild. We can revisit hiding the default gentoo python at a later time.
