### ISSUE TITLE
Converting internal MediaWiki documentation to public Markdown documentation on Github

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#31]
These pages could be converted : 
https://wiki.computecanada.ca/staff/Software_installation

**Comment by mboisson** [comment]
Probably should link to this page as well https://github.com/ComputeCanada/wheels_builder

**Comment by ofisette** [comment]
I will start work on the TECC wiki side, putting redirects on the pages that were moved and reworking the “Software Installation” page to link GitHub and not duplicate information.

> Probably should link to this page as well https://github.com/ComputeCanada/wheels_builder

It is already linked on the Python page.

**Comment by ofisette** [comment]
I replaced all affected TECC wiki pages with “soft” redirects (hard redirects only work with wiki links). I updated all links pointing to affected pages to point to GitHub instead. I simplified the “Setup” page to avoid duplicated information. Finally, I updated the main “Software Installation” page to point to GitHub.

I think this is everything, but we could do with a last check before closing.

**Comment by ofisette** [comment]
No one has cried out in pain, I think we can close this.
