### ISSUE TITLE
Custom mountpoints for clusters

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/software-stack#32]
We would like to supplement the EBS-backed NFS storage with FSx on AWS (lots of abbreviations there...).

Is there support currently for custom mountpoints, such that they would be added to new compute node instances as they are provisioned? If not, where should be start looking in the Puppet code?

I know you plan to add things like FSx in the future but hopefully this would be enough for us in the meantime.

**Comment by mboisson** [comment]
You probably meant this to go to the magic castle repository ?
  

  
  

  
  
>

**Comment by mboisson** [comment]
Re-created here https://github.com/ComputeCanada/magic_castle/issues/111
