### ISSUE TITLE
Documenting StdEnv

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#36]
With now 3 different software environments, documentation is needed to be able to point users to to make the switch. 

This is the first draft for this page : https://docs.computecanada.ca/wiki/Standard_software_environments#What_are_standard_software_environments_.3F

**Comment by stubbsda** [comment]
I think the biggest question many users would have is, "If I switch to another (more modern) software environment - or am forced to do so by CC - will I need to reinstall all/some of my software stack?" This is particularly an issue for those who have an elaborate chain of R packages or Python virtual environments in their home directory.

**Comment by mboisson** [comment]
> I think the biggest question many users would have is, "If I switch to another (more modern) software environment - or am forced to do so by CC - will I need to reinstall all/some of my software stack?" This is particularly an issue for those who have an elaborate chain of R packages or Python virtual environments in their home directory.

Added a section about this.

**Comment by rmdickson** [comment]
I like it.  The following are mere quibbles about word-choice, and I'd be happy to make the changes myself if you like.

Section StdEnv/2016.4 refers to "primary" compilers and MPI, sections on 2018 and 2020 use "default".  I think I prefer the "default" language.

"Performance optimization[s]" appears in a few places.  I would prefer "Performance improvement[s]".  "Optimization" implies perfection to me, which I don't like to promise.  Or even imply :-)

"Change in the compatibility layer" ends mid-sentence: "This change" ...

**Comment by mboisson** [comment]
Yes, feel free to wordsmith as you see fit.

**Comment by mboisson** [comment]
The bulk of this is done. The rest will be adjustments.
