### ISSUE TITLE
Recent toolchain without Intel?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/software-stack#37]
For one of our use cases, the `non-commercial` requirement for the `Intel` compiler may be a problem.

At the moment loading `StdEnv/2020` but unloading `intel/2020.1.217` means there is no MPI support.

**Comment by mboisson** [comment]
There is MPI support if you load GCC/9.3.0, aka if you use variants of the `gomklc,2020a` toolchain.

**Comment by mboisson** [comment]
Feel free to reopen if it does not work for you.

**Comment by verdurin** [comment]
This did work, with `gcc/9.3.0` - it didn't find the upper-case version.

Seems as though `StdEnv` is the main supported approach - I didn't manage to find any modules for `gomklc`?

**Comment by mboisson** [comment]
Our toolchains are hidden. `module --show-hidden avail` will show them all. But EasyBuild really does not care about whether the module is hidden or not. The only thing you should know is that if you want to use the `2020a` toolchains, you should ensure that the `gentoo` module is loaded, while if you want to install with former toolchain versions, you should probably use `nixpkgs`. Former toolchain versions were also a bit of a mess, with things like `gomklc,2018.3.312.102`  to mean GCC 7.3 + OpenMPI 3.1.2 + Cuda 10.2. I would recommend starting with the `2020a` toolchains which use all of the same versions as upstream EasyBuild.

**Comment by verdurin** [comment]
Thanks for the background. Was indeed planning to build on what's available already in `2020a`. This is bioinformatics, so naturally some of what they want isn't available yet...

**Comment by mboisson** [comment]
If you have specific packages, I am currently rebuilding a lot of packages, and a lot of them are bioinformatics, as you may expect.

**Comment by mboisson** [comment]
By the way, a lot of those packages will be compiled using the `GCCcore,9.3.0` toolchain, since it gets CPU architecture optimizations, and this makes them available irrespective of the compiler module loaded.
