### ISSUE TITLE
Hiding module extensions from the output of `module avail` 

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#45]
Since we enabled module extensions, they dominate the output of `module avail`. It would be best if those were shown only through module spider.

**Comment by mboisson** [comment]
This requires updating Lmod to 8.4.12: 
https://github.com/TACC/Lmod/commit/82dbe9f89ac4f78e219bd6415654f2a140d73f0a

**Comment by bartoldeman** [comment]
Lmod upgraded to 8.4.12:
https://github.com/ComputeCanada/software-stack-custom/commit/5836ca01cd80e153ee2ece57e143c4d859fca6e2
Set env var (LMOD_AVAIL_EXTENSIONS=no)
https://github.com/ComputeCanada/software-stack-config/commit/f3a8712dffcc1b67bcfe93ba1d14fa3cfaaea441
