### ISSUE TITLE
All extensions show up in `module keyword` results

### ISSUE THREAD

**Issue by ofisette** [ComputeCanada/software-stack#46]
All extension modules show up in the output of `module keyword <blerg>`, in addition to the expected search results. I believe this started when packages such as `scipy-stack` were improved by adding extensions.

**Comment by mboisson** [comment]
This is a bug in Lmod. I reported it. We will need to update Lmod once a new release is available.

**Comment by mboisson** [comment]
According to Robert : 
```
I have updated Lmod to fix this bug.  Thanks for pointing it out.  Please test Lmod 8.4.16 to see if it fixes this issue for you.
``` 

@bartoldeman, we are due for another Lmod update :P
