### ISSUE TITLE
Make ipython-kernel module sticky in JupyterHub context

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/software-stack#47]
JupyterLab launcher requires at least one Python kernel to be in JUPYTER_PATH to work. If no kernel is found, the launcher is entirely blank.

It is currently possible for a user to unload the ipython-kernel module through jupyter-lmod and break the JupyterLab launcher. It would be nice to be able to make ipython-kernel _sticky_ to avoid breaking JupyterLab launcher.

**Comment by mboisson** [comment]
What is the safe way of figuring out if we are in the Jupyter context ? Checking for non-emptiness of `JUPYTER_PATH` is circular, since it is defined by `ipython-kernel`

**Comment by cmd-ntrf** [comment]
There are a few SLURM environment variables that include clues:
```
SLURM_JOB_NAME=spawner-jupyterhub
SLURM_SUBMIT_DIR=/run/jupyterhub
SLURM_SUBMIT_HOST=jupyterhub.int.ets1.calculquebec.ca
```

Also the presence of these variables are a good indicator that the job was submitted through JupyterHub
```
JUPYTERHUB_API_TOKEN
JPY_API_TOKEN
JUPYTERHUB_CLIENT_ID
JUPYTERHUB_HOST
JUPYTERHUB_OAUTH_CALLBACK_URL
JUPYTERHUB_USER
JUPYTERHUB_SERVER_NAME
JUPYTERHUB_API_URL
JUPYTERHUB_ACTIVITY_URL
JUPYTERHUB_BASE_URL
JUPYTERHUB_SERVICE_PREFIX
```

**Comment by mboisson** [comment]
Is it just `ipython-kernel` that must be sticky ? or also `python` and `ipykernel` ?

**Comment by cmd-ntrf** [comment]
I think `ipython-kernel` is sufficient, but we would have to test to be sure.

**Comment by mboisson** [comment]
Done in https://github.com/ComputeCanada/easybuild-easyconfigs/commit/b03ff2c8a1b88e148e90d58318f64f8bda17e913

Reinstalling and redeploying.

**Comment by mboisson** [comment]
This is now deployed. Can you verify if it fixes the issue ?

**Comment by mboisson** [comment]
@plstonge or @cmd-ntrf, do you know how to reproduce the issue and if it still happens ?

**Comment by cmd-ntrf** [comment]
I can still unload ipython-kernel on Beluga's JupyterHub and break the launcher.

**Comment by mboisson** [comment]
Ah, I only fixed it in the 2020 environment, which is why it seemed to work for me.

**Comment by plstonge** [comment]
I think the problem came from migrating between `StdEnv` modules, but I have not seen the problem recently. I believe the problem appeared with a normal/legitimate module change, and not by removing ipython-kernel explicitly.

**Comment by mboisson** [comment]
@plstonge this should now be solved.
