### ISSUE TITLE
vncserver always default to display :1 in Slurm jobs because users have isolated /tmp

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/software-stack#48]
`vncserver` looks in /tmp to determine the display number automatically if no number have been provided.

On Compute Canada clusters. the Slurm plugin [`spank-cc-tmpfs_mounts`](https://github.com/ComputeCanada/spank-cc-tmpfs_mounts) isolates users `/tmp/`. Therefore, vncserver always default to `:1` which might not be available if another user already have an active X display.

`vncserver` is a perl script. The subroutine `CheckDisplayNumber` on line 524 is responsible for checking if a given display number is available. This subroutine is called by `GetDisplayNumber` which is a essentially a for loop on indices 1 to 99 that returns the first available display number for which CheckDisplayNumber returns 1.

I propose we add a check in `CheckDisplayNumber` that would look at the output of the `ss` command which would correctly list the display file opened in other users `/tmp`.

Something like this:
```perl
    if (system("ss | grep -q '/tmp/.X11-unix/X$n") == 1) {
        warn "\nWarning: $host:$n is taken by another process\n";
        return 0;
    }
```

The exact syntax would have to be double-checked since Perl is definitely not my first language.

**Comment by mboisson** [comment]
The correct patch to apply is this one : 
```diff -ru /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/vncserver vncserver
--- /cvmfs/soft.computecanada.ca/gentoo/2020/usr/bin/vncserver	2021-04-12 11:39:41.000000000 -0400
+++ vncserver	2021-05-18 12:23:34.000000000 -0400
@@ -504,6 +504,12 @@
 sub CheckDisplayNumber
 {
     local ($n) = @_;
+    my @output = `ss`;
+    if (grep( /\/tmp\/.X11-unix\/X$n /, @output) != 0) {
+        warn "\nWarning: $host:$n is taken by another process\n";
+        return 0;
+    }
+

     socket(S, $AF_INET, $SOCK_STREAM, 0) || die "$prog: socket failed: $!\n";
     eval 'setsockopt(S, &SOL_SOCKET, &SO_REUSEADDR, pack("l", 1))';```

**Comment by mboisson** [comment]
This should now be fixed.
