### ISSUE TITLE
Correct behavior for OMPI + Slurm 20.11 using OMPI MCA parameters

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#49]
This is to be done after the holidays. Instead of using `SLURM_WHOLE=1`  it is possible to use `OMPI_MCA_plm_slurm_args="--whole"`, which is more specific to OMPI.

**Comment by mboisson** [comment]
https://github.com/open-mpi/ompi-www/pull/342#issuecomment-746773927

**Comment by bartoldeman** [comment]
I pushed the fix and will deploy to dev now, not prod yet.
