### ISSUE TITLE
Changing the default software environment to StdEnv/2020

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#50]
First on build-node.

**Comment by mboisson** [comment]
The relevant commit is: https://github.com/ComputeCanada/software-stack-config/commit/ff6736bdc0b5d7f53a4d99c1c62aa2342dc27d6f

**Comment by gshamov** [comment]
The depreciation warning is  now , at least on the build-node, fired for any SSH connection including non-interactive sessions like SCP. I think it is unintended and perhaps should be fixed.

**Comment by mboisson** [comment]
@bartoldeman, I am not sure how to test for interactive shell in Lua. I am thinking that the proper fix to @gshamov's issue is to change
`module --initial_load restore` 
by
`module -q --initial_load restore` 
here: 
https://github.com/ComputeCanada/software-stack-config/blob/ff6736bdc0b5d7f53a4d99c1c62aa2342dc27d6f/profile.d/z-20-lmod.csh#L26
and here: 
https://github.com/ComputeCanada/software-stack-config/blob/ff6736bdc0b5d7f53a4d99c1c62aa2342dc27d6f/profile.d/z-20-lmod.sh#L22

Thought ?

**Comment by mboisson** [comment]
Another question is what to do with legacy clusters that may not have enough modules compiled with the 2020 environment for their CPU architecture. 

@gshamov, @hzlucq, @alikerr @ofisette do you think that's an issue for your sites ?

**Comment by mboisson** [comment]
> @bartoldeman, I am not sure how to test for interactive shell in Lua. I am thinking that the proper fix to @gshamov's issue is to change
> `module --initial_load restore`
> by
> `module -q --initial_load restore`
> here:
> https://github.com/ComputeCanada/software-stack-config/blob/ff6736bdc0b5d7f53a4d99c1c62aa2342dc27d6f/profile.d/z-20-lmod.csh#L26
> and here:
> https://github.com/ComputeCanada/software-stack-config/blob/ff6736bdc0b5d7f53a4d99c1c62aa2342dc27d6f/profile.d/z-20-lmod.sh#L22
> 
> Thought ?

Simply this does not work, since it makes every login quiet, which goes against the idea of warning users.

**Comment by mboisson** [comment]
@gshamov's problem is fixed in 
https://github.com/ComputeCanada/software-stack-config/commit/967317bee884fe647947afd2c2ab69f26fc92369

but I don't know how to make the same test for the csh startup script.

**Comment by joeydumont** [comment]
I was curious... It seems that the prompt variable is only set in
interactive shels in csh (https://unix.stackexchange.com/a/26686).

**Comment by mboisson** [comment]
Thanks. Yes, a colleague pointed this out as well. I can make the change, but my issue is testing it, as very few (~2) of our users use csh as their login shell.

**Comment by mboisson** [comment]
I have done that in https://github.com/ComputeCanada/software-stack-config/commit/65461b208abf6e3d145217a40f1d1e17716caeec

**Comment by bartoldeman** [comment]
we can probably create a local account on  build-node with *csh as the login shell.
I'll try this

**Comment by bartoldeman** [comment]
@mboisson try `sudo -iu cshuser` on build-node

**Comment by bartoldeman** [comment]
or put your ssh public key in the account to simulate a user login properly

**Comment by mboisson** [comment]
Ok, that worked as expected. The message is shown with an interactive login, and is not shown in a non-interactive one (i.e. with scp)

**Comment by mboisson** [comment]
Now, I need to test a new version of Lmod. 
https://github.com/TACC/Lmod/tree/wV

This is to be able to distinguish between a default version that comes from the users' files from a default version that comes from global.

**Comment by mboisson** [comment]
I now use the new feature (only if Lmod version is recent enough, to avoid breakage on Niagara). I also display the message in French or in English based on LANG. 

https://github.com/ComputeCanada/software-stack-config/commit/aed5b641ef46730e2cfe9b1abc307ccf30ed7da1

**Comment by mboisson** [comment]
This is now deployed to dev for testing on clusters.

**Comment by mboisson** [comment]
Code has been deployed to production, but it is disabled unless the environment variable 
`RSNT_ENABLE_STDENV2020_TRANSITION="yes"` 
is defined. This is to allow testing in full production. It also allows a site to disable the transition warning once we do decide to enable it on all of our clusters.

**Comment by mboisson** [comment]
The code is now enabled on our clusters.

**Comment by mboisson** [comment]
Pull request for making the switch on April 1st is here: https://github.com/ComputeCanada/software-stack-config/pull/4

**Comment by mboisson** [comment]
Note this related issue: https://github.com/ComputeCanada/software-stack/issues/62

**Comment by mboisson** [comment]
This is now done.
