### ISSUE TITLE
Prevent publishing operations while stratum0 garbage collection is running

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#54]
@rptaylor

**Comment by mboisson** [comment]
An "abort transaction" operation was issued from the build node while the nightly garbage collector operation was running on the dev stratum0. This may have corrupted some catalogs. "abort transaction" operations are automatically issued when someone exits from the `libuser` account. 

Measures need to be taken in the future to avoid this. Possible options are
1) On the stratum0, block incoming ssh/sshfs operations while the GC is running
2) On the build-node, block the librarian account during specific time windows
3) Implement some logic on the build-node to figure out whether an existing transaction was started by the current session or not, and only abort transaction upon logout if it was started by the current session.

**Comment by rptaylor** [comment]
https://sft.its.cern.ch/jira/browse/CVM-1967

**Comment by rptaylor** [comment]
Another way to avoid this would be to provide an "escape hatch" (logout without aborting). If someone attempts to start a transaction and sees the message that a transaction is already in progress , they can/should exit without aborting the transaction.

**Comment by mboisson** [comment]
I would rather not rely on the person doing the right thing, and instead somehow completely prevent the mistake from happening.

**Comment by rptaylor** [comment]
Well that is an implementation detail. You could do it either way.
```
$ sudo cvmfs_server transaction  test.dev.computecanada.ca
Repository test.dev.computecanada.ca is already in a transaction
$ echo $?
1
```
If the exit code from starting a transaction is 1 , the scriptage could exit without aborting.  That approach relies on the assumption that all RSNT transactions are aborted when someone logs out of libuser.  However I am starting to question whether a silent implicit abort on logout is a good idea. Perhaps printing a message "Aborting all transactions, please wait until this completes" would help.

**Comment by mboisson** [comment]
We already can test whether it is in a transaction. What we don't know is if the transaction was started externally from us or not. We do want to abort all and any transaction started by us. I would prefer that the stratum0 block communications while GC is ongoing. There is also the question of whether GC can start while a transaction is already ongoing.

**Comment by rptaylor** [comment]
No, GC is a transaction so it is blocked just like any other attempt to do multiple transactions.
`Cannot run garbage collection while in a transaction`.  
If abort merely stops  the GC or prevents from running one night, it's not such a big problem.

**Comment by rptaylor** [comment]
I tested running GC and aborting it. The GC process was terminated as expected:
```
$ sudo cvmfs_server gc -t "30 days ago"  soft-dev.computecanada.ca
YOU ARE ABOUT TO DELETE DATA! Are you sure you want to do the following:
Affected Repositories:         soft-dev.computecanada.ca 
Dry Run (no actual deletion):  no
Needs Reflog reconstruction:   no
Preserve Revisions newer than: 12/21/20 13:35:12

Please confirm this action (y/N)? y
Running Garbage Collection 
  --> marking unreferenced objects [Wed, 20 Jan 2021 21:35:20 GMT]
garbage collection failed
Segmentation fault
Fail (6)!
umount: /cvmfs/soft-dev.computecanada.ca: not mounted

Broadcast message from root@lyresponge.comp.uvic.ca (Wed Jan 20 13:35:50 2021):

soft-dev.computecanada.ca is forcefully remounted in 60 seconds.
Please close files on /cvmfs/soft-dev.computecanada.ca

Broadcast message from root@lyresponge.comp.uvic.ca (Wed Jan 20 13:36:50 2021):

soft-dev.computecanada.ca is forcefully remounted NOW.
```

The abort operation also completed successfully:
```
$ sudo cvmfs_server abort soft-dev.computecanada.ca
[sudo] password for xrpt: 
You are about to DISCARD ALL CHANGES OF THE CURRENT TRANSACTION for soft-dev.computecanada.ca!  Are you sure (y/N)? y

Broadcast message from root@lyresponge.comp.uvic.ca (Wed Jan 20 13:35:50 2021):

soft-dev.computecanada.ca is forcefully remounted in 60 seconds.
Please close files on /cvmfs/soft-dev.computecanada.ca
```

But the success of both operations relies on patiently allowing them to complete without interruption during the 60 second waiting period. Of course seeing the output helps; it is broadcast so that all logged in users can see it , but that may not get transmitted over the SSH interface. 

Most likely cancelling the abort operation and/or doing other operations while the automatic recovery (forceful remount) was in progress led to the problematic state. The forceful unmount and remount could have broken the sftp mount, or the SFTP mount may have interfered with the repository recovery, after which there are various reasons publish could have hung indefinitely.

I don't think the SSH interface and associated scriptage can be made fully robust for all eventualities, it is just what we came up with at the time as a way to make things work. We should transition to the gateway interface instead which will be better supported, and provide direct access to server commands with full input and output.

**Comment by rptaylor** [comment]
Or, cancelling the abort operation by Ctrl+C during the libuser logout may have simply stopped the automatic recovery from happening.

**Comment by rptaylor** [comment]
For the record, helpfully provided logs of the sequence of events:
```

[@build-node:~/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS]
$ sudo  su - libuser                                                                                                               
Last login: Tue Jan 19 00:48:04 NST 2021 on pts/29
[libuser@build-node ~]$ sudo /etc/rsnt/start_transaction dev
Repository soft-dev.computecanada.ca is already in a transaction
[libuser@build-node ~]$ logout
​
^CKilled by signal 2.
^CKilled by signal 2.
^C^C[@build-node:~/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS]
$ ^C
[@build-node:~/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS]
$ ^C
[@build-node:~/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS]
$ ^C
[@build-node:~/easybuild-easyconfigs/easybuild/easyconfigs/g/GROMACS]
$ sudo  su - libuser
Last login: Tue Jan 19 06:30:20 NST 2021 on pts/25
libuser account already used by user 
not mounting the filesystems again
[libuser@build-node ~]$ sudo /etc/rsnt/abort_transaction dev                                                                       
/var/spool/cvmfs/soft-dev.computecanada.ca/rdonly is not mounted properly.
/cvmfs/soft-dev.computecanada.ca is not mounted properly.
soft-dev.computecanada.ca is in a transaction but /cvmfs/soft-dev.computecanada.ca is not mounted read/write
Note: Trying to mount /var/spool/cvmfs/soft-dev.computecanada.ca/rdonly... ^CKilled by signal 2.
[libuser@build-node ~]$ exit
logout
Repository soft-dev.computecanada.ca is not in a transaction
Repository soft.computecanada.ca is not in a transaction
Repository restricted.computecanada.ca is not in a transaction
Repository data.rsnt.computecanada.ca is not in a transaction
```

**Comment by mboisson** [comment]
This is now fixed in 
https://git.computecanada.ca/rsnt-software/rsnt-scripts/-/commit/eb53e5c12cf38c20620b8919530da611e6e6e9af

@rptaylor, you can review the code if you wish. Let me know if you find issues.
