### ISSUE TITLE
 Bioinformatics National Team non-CC staff access

### ISSUE THREAD

**Issue by jshleap** [ComputeCanada/software-stack#55]
The Bioinformatics National Team is thinking about reviving the biorepository, which includes the deployment of several biological datasets. Our team is diverse and includes CC and non-CC staff. We are requesting access to a build-node (perhaps a new VM?) or access for non-CC staff that are part of the BNT for dataset management. The management of datasets requires a significant amount of space as well.
Thoughts?

**Comment by mboisson** [comment]
Following discussions (20210212), the BNT will use its own infrastructure, with its own repository for datasets. Therefore, non-CC staff access to the build node is no longer required. Further discussions with the RSNT about the documentation and about how to integrate dataset modules with software modules will happen once the BNT and CVMFS teams are ready to go further.

Closing this specific issue for now.
