### ISSUE TITLE
Renaming "master" to "main" in our repositories

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#57]
https://github.com/github/renaming

After the branch is renamed on Github, people have to run : 
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by mboisson** [comment]
List of repositories and branches to rename : 

- [ ] https://github.com/ComputeCanada/wheels_builder/tree/master
- [ ] https://github.com/ComputeCanada/easybuild-computecanada-config/tree/master
- [ ] https://github.com/ComputeCanada/easybuild-easyconfigs/tree/computecanada-master
- [ ] https://github.com/ComputeCanada/easybuild-easyblocks/tree/computecanada-master
- [ ] https://github.com/ComputeCanada/software-stack-custom/tree/master
- [ ] https://github.com/ComputeCanada/software-stack-config/tree/master
- [ ] https://github.com/ComputeCanada/easybuild-framework/tree/computecanada-master
- [ ] https://github.com/ComputeCanada/gentoo-overlay/tree/master
- [ ] https://github.com/ComputeCanada/wiki_module_bot/tree/master

Not sure if we should rename those: 
- [ ] https://github.com/ComputeCanada/easybuild-easyconfigs/tree/master
- [ ] https://github.com/ComputeCanada/easybuild-easyblocks/tree/master
- [ ] https://github.com/ComputeCanada/easybuild-framework/tree/master

**Comment by bartoldeman** [comment]
All done

**Comment by mboisson** [comment]
For documentation purpose, this is what needs to be done on your local forks : 
```
git branch -m computecanada-master computecanada-main
git fetch origin
git branch -u origin/computecanada-main computecanada-main
``` 

and
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by ofisette** [comment]
Following this change, clean clone of several repositories, including `software-stack`, behave strangely. For instance:

**Comment by ofisette** [comment]
Following this change, clean clones of several repositories including `software-stack`, behave strangely:
```
$ git clone https://github.com/ComputeCanada/software-stack/
$ git branch
* main
$ git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged.
[...]
```

**Comment by mboisson** [comment]
🤔 
```
[mboisson@build-node tmp]$ git clone https://github.com/ComputeCanada/software-stack/
Clonage dans 'software-stack'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 81 (delta 28), reused 32 (delta 9), pack-reused 0
Réception d'objets: 100% (81/81), 339.68 Kio | 1.64 Mio/s, fait.
Résolution des deltas: 100% (28/28), fait.
[mboisson@build-node tmp]$ cd software-stack/
[mboisson@build-node software-stack]$ git branch
* main
[mboisson@build-node software-stack]$ git pull
Déjà à jour.
```

**Comment by mboisson** [comment]
You didn't `cd` to `software-stack` in your example

**Comment by ofisette** [comment]
I did `cd` in the directory, but forgot to add it to the example. However, you are right, this is due to being in an existing repository; I cloned somewhere else and it worked. I use Git to track config files in my home directory and it seems this `master -> main` change somehow conflicts with my local repo when the repos are nested. I will close since this is likely a problem with my local Git config. (Although it did work with no issues before the branch renaming.)

**Comment by lemairecarl** [comment]
The master branch still exists in wheels_builder:
https://github.com/ComputeCanada/wheels_builder/tree/master

**Comment by lemairecarl** [comment]
`git checkout master` was still working on my laptop even after deleting the branch on GitHub, and deleting the local branch on my laptop. I found that I had to do `git fetch --prune`.

**Comment by mboisson** [comment]
There isn't much we can do about this. It is an alias I think.

**Comment by ccoulombe** [comment]
Git being a distributed version control system, you have your own full copy on your laptop. You then need to fetch with the origin and remove deleted branch.

**Comment by lemairecarl** [comment]
The situation was different in wheels_builder than in the other repos. It seemed like master was really there. The link https://github.com/ComputeCanada/wheels_builder/tree/master was working normally, without redirecting to "main". Maybe somebody pushed the branch by mistake at some point?

Anyways, nothing to see here, it's fixed now. (I removed the branch from the github interface)
