### ISSUE TITLE
Lmod should not depend on anything in Nix or Gentoo

### ISSUE THREAD

**Issue by bartoldeman** [ComputeCanada/software-stack#6]
Since Lmod is loaded before everything else it should only depend on some minimal glibc (we chose CentOS-6 glibc 2.17 to still be compatible to that), and be otherwise self-contained.

I therefore compiled a new Lmod in `/cvmfs/soft.computecanada.ca/custom/software/lmod` as follows:

1. Login to CentOS-6 server and setup proot:
```
wget https://github.com/proot-me/proot-static-build/releases/download/v5.1.1/proot_5.1.1_x86_64_rc2--no-seccomp
mv proot_5.1.1_x86_64_rc2--no-seccomp proot
chmod +x proot
./proot -b $HOME/software:/cvmfs/soft.computecanada.ca/custom/software bash
```

2. Compile Lua statically (requires `ncurses-static` and `readline-static` RPMs installed on server)
```
wget https://sourceforge.net/projects/lmod/files/lua-5.1.4.9.tar.bz2
tar xf lua-5.1.4.9.tar.bz2
cd lua-5.1.4.9
./configure --prefix=/cvmfs/soft.computecanada.ca/custom/software/lua --with-static=yes
make install
```

3. Compile TCL
```
wget https://sourceforge.net/projects/tcl/files/Tcl/8.6.10/tcl8.6.10-src.tar.gz
tar xf tcl8.6.10-src.tar.gz
cd tcl8.6.10/unix
./configure --prefix=/cvmfs/soft.computecanada.ca/custom/software/tcl
make install
```

4. Compile Lmod with special options for tcl2lua.so
```
wget https://github.com/TACC/Lmod/archive/8.3.8.tar.gz
tar xf 8.3.8.tar.gz
cd Lmod-8.3.8/
./configure --with-duplicatePaths=yes --with-caseIndependentSorting=yes --with-redirect
=yes --with-module-root-path=/cvmfs/soft.computecanada.ca/easybuild/modules --prefix=/cvmfs/soft.computecanada.ca/
custom/software
make -C pkgs/tcl2lua LUA_INC=/cvmfs/soft.computecanada.ca/custom/software/lua/include DIR=/cvmfs/soft.computecanada.ca/custom/software/tcl/include LIBS="-L/cvmfs/soft.computecanada.ca/custom/software/tcl/lib -Wl,-rpath,/cvmfs/soft.computecanada.ca/custom/software/tcl/lib -ltcl8.6"
make install
```
5. Transfer $HOME/software to build-node, set `MODULESHOME=/cvmfs/soft.computecanada.ca/custom/software/lmod/lmod`.

Note: if only Lmod is upgraded and the CentOS-6 server mounts cvmfs, steps 2-3 can be skipped.

Any comments @mboisson ?

**Comment by mboisson** [comment]
So, with this, the following are the dependencies that get resolved in the OS assuming no module is loaded : 
```
      1 libcrypt.so.1 => /lib64/libcrypt.so.1
     21 libc.so.6 => /lib64/libc.so.6
      5 libdl.so.2 => /lib64/libdl.so.2
      1 libfreebl3.so => /lib64/libfreebl3.so
      4 libm.so.6 => /lib64/libm.so.6
      6 libpthread.so.0 => /lib64/libpthread.so.0
      1 librt.so.1 => /lib64/librt.so.1
      4 libz.so.1 => /lib64/libz.so.1
``` 

Could we put those from CentOS6 in a directory on CVMFS (outside of nix and gentoo) and add RPATH to the libraries, so that they get resolved on CVMFS still ?

**Comment by bartoldeman** [comment]
@mboisson how did you get this information? All the above are part of glibc with the exception of libz and libfreebl3 so I'd like to know how they get loaded.

I'd like to avoid adding glibc CentOS6 libraries in CVMFS, since a) glibc is guaranteed to be available on all nodes (unlike libreadline, libncurses etc, which is why I linked those statically) b) it is backwards compatible, and c) there won't be any security updates

**Comment by mboisson** [comment]
I ran `ldd` on all `.so*` in the `custom` directory.

**Comment by mboisson** [comment]
```for f in $(find /cvmfs/soft.computecanada.ca/custom/software/{lmod,lua,tcl} -name '*.so*'); do echo $f; ldd $f; done | grep lib | sort | awk '{print $1, $2, $3}' | uniq -c```

**Comment by bartoldeman** [comment]
thanks. libfreebl3 is an indirect dependency of libcrypt so not an issue.
libz comes from TCL, which I'd like to eliminate, so I'll recompile TCL.

**Comment by bartoldeman** [comment]
I managed to get it working with a much more minimal static TCL. The list is as follows now:

```
      1 libcrypt.so.1 => /lib64/libcrypt.so.1
     13 libc.so.6 => /lib64/libc.so.6
      1 libdl.so.2 => /lib64/libdl.so.2
      1 libfreebl3.so => /lib64/libfreebl3.so
      1 libpthread.so.0 => /lib64/libpthread.so.0
      1 librt.so.1 => /lib64/librt.so.1
```

**Comment by mboisson** [comment]
What about the libraries other than `libc.so.6` ? are those guaranteed to be there as well ?

**Comment by bartoldeman** [comment]
Yes that's what I said, they are all part of glibc. The only exception in that list is `libfreebl3.so` but it's an indirect dependency of libcrypt in CentOS-7, not named directly in posix.so. To get the real list we need this command:
```
for f in $(find /cvmfs/soft.computecanada.ca/custom/software/{lmod,lua,tcl} -name '*.so*'); do echo $f; patchelf --print-needed $f; done | grep lib | sort | awk '{print $1, $2, $3}' | uniq -c
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/tcl2lua.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/tcl2lua.so.1  
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/tcl2lua.so.1.0.1  
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/term/core.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/term/core.so.1  
      1 /cvmfs/soft.computecanada.ca/custom/software/lmod/8.3.8/lib/term/core.so.1.0.1  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/lfs.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/lpeg.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/posix.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/profiler.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/sys.so  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/sys.so.1  
      1 /cvmfs/soft.computecanada.ca/custom/software/lua/lib/lua/5.1/sys.so.1.0.1  
      1 libcrypt.so.1  
     13 libc.so.6  
      1 librt.so.1  
```

**Comment by mboisson** [comment]
Ok. When we need to update Lmod, what needs to be done ? Can we somehow automate this ?

**Comment by mboisson** [comment]
Sounds like it would be a good match to run the build procedure in a singularity container ?

**Comment by rjeschmi** [comment]
@mboisson mentioned this too me. I think it is definitely possible and pretty similar to what conda (and conda forge in particular) does. I'll see if I can find any issues on which centos they settled on. I feel like I saw some tickets with them being dragged along by what was available on travis, but it might be worth comparing notes.

I've seen some minor discrepancies in SLES, but that probably isn't a big deal to you guys I imagine.

Do you think there are any dynamically loaded libraries that might be hard to detect using readelf in lua in particular? lfs and posix are the two I recalled specifically with lua and lmod compatibility, but I wonder if there are any others.

I'll look into this out of interest too and see if I see anything.

**Comment by bartoldeman** [comment]
yes singularity could do it. I'll check if I can do that on build-node.

**Comment by bartoldeman** [comment]
@rjeschmi well it should work on SLES as well -- for lua we specifically looked at deps of the posix and lfs shared objects. The lua binary is linked statically to everything except glibc.

**Comment by rjeschmi** [comment]
glibc on centos6 is 2.12. I think that is too old. 2.17 would be fine though (if you can make that assumption everywhere you are good).

https://github.com/conda/conda-build/issues/3696

Issues like the removal of vsyscall so it won't work on newer oses that don't support it.

**Comment by verdurin** [comment]
Seems like you have this one in hand, not much I can add.

Happy to test.

We don't have anything older than CentOS 7.

**Comment by bartoldeman** [comment]
As far as I know there is no issue using glibc-2.12 at compile time but a newer glibc at runtime. The issue that @rjeschmi refers to is specifically statically linking to glibc-2.12.

Using a copy of glibc-2.12 could give similar issues on new kernels I guess, but it's just not necessary.

I've reproduced the build using singularity (which I installed using an rpm on the build node) and also eliminated dependencies on all libraries except `libc.so.6` and, for `lua` and `tclsh`, `libm` and `libdl`.  All the scripts are on build-node in `/cvmfs/soft.computecanada.ca/custom/sources` (see README.txt there) but I should put it on git somewhere, do you have a good suggestion @mboisson as our gitlab is hidden?

**Comment by rjeschmi** [comment]
So I tested it in Docker and it works fine for my tests. I had to make some small modifications from what @bartoldeman suggested (tcl.h wasn't found in the configure step and setting the luarocks paths, that I got from the command `luarocks path`. I wonder if you picked up some deps in the environment by accident. In your environment that may be portable anyway.

It works in general, but I'll try some vm tests tomorrow to see if I can find a vm that doesn't emulate vsyscall and will generate the issue (I assume the kernel in my modern ubuntu box is emulating it fine or at least is consistent between the two versions).

https://github.com/rjeschmi/docker-lmod/blob/static/Dockerfile

The docker build is happening from that and will show up in rjeschmi/lmod:centos6 at some point or can be build with the docker-compose file.

It has been a long time since I looked at this stuff :)

```
$ objdump -x $(which lua)
Version References:
  required from libdl.so.2:
    0x09691a75 0x00 06 GLIBC_2.2.5
  required from libc.so.6:
    0x0d696913 0x00 05 GLIBC_2.3
    0x0d696917 0x00 04 GLIBC_2.7
    0x09691a75 0x00 03 GLIBC_2.2.5
  required from libm.so.6:
    0x09691a75 0x00 02 GLIBC_2.2.5
```

**Comment by bartoldeman** [comment]
@rjeschmi 
here are the scripts that I used in the end (which solve the tcl.h issue since I now used a minimal singularity image):

```
#!/bin/sh
mkdir /tmp/build-lua
cd /tmp/build-lua
tar xf /cvmfs/soft.computecanada.ca/custom/sources/lua-5.1.4.9.tar.bz2
cd lua-5.1.4.9
patch -p1 < /cvmfs/soft.computecanada.ca/custom/sources/luaposix-disable-rt-crypt.patch
./configure --prefix=/cvmfs/soft.computecanada.ca/custom/software/lua --with-static=yes
rm -rf /cvmfs/soft.computecanada.ca/custom/software/lua
make install
cd ..
rm -rf /tmp/build-lua
```

```
#!/bin/sh
mkdir /tmp/build-tcl
cd /tmp/build-tcl
tar xf /cvmfs/soft.computecanada.ca/custom/sources/tcl8.6.10-src.tar.gz
cd tcl8.6.10/unix
./configure --prefix=/cvmfs/soft.computecanada.ca/custom/software/tcl --disable-shared --disable-threads
rm -rf /cvmfs/soft.computecanada.ca/custom/software/tcl
make install-binaries install-libraries install-headers
ln -s tclsh8.6 /cvmfs/soft.computecanada.ca/custom/software/tcl/bin/tclsh
cd ..
rm -rf /tmp/build-tcl
```

```
#!/bin/sh
mkdir /tmp/build-lmod
cd /tmp/build-lmod
CUSTOM=/cvmfs/soft.computecanada.ca/custom
LUA=/cvmfs/soft.computecanada.ca/custom/software/lua
TCL=/cvmfs/soft.computecanada.ca/custom/software/tcl
tar xf $CUSTOM/sources/Lmod-8.3.8.tar.gz
cd Lmod-8.3.8
export CPATH=$TCL/include
export LIBRARY_PATH=$TCL/lib
export PATH=$TCL/bin:$LUA/bin:$PATH
./configure --with-duplicatePaths=yes --with-caseIndependentSorting=yes --with-redirect=yes --with-module-roo
t-path=/cvmfs/soft.computecanada.ca/easybuild/modules --prefix=$CUSTOM/software LIBS="-lm -ldl"
rm -f $CUSTOM/software/lmod
make install
cd ..
rm -rf /tmp/build-lmod
```

Def file for singularity:
```
BootStrap: yum
OSVersion: 6 
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/x86_64/
Include: yum

# If you want the updates (available at the bootstrap date) to be installed
# inside the container during the bootstrap instead of the General Availability
# point release (6.x) then uncomment the following line
#UpdateURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/updates/$basearch/


%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
    rm -rf /var/lib/rpm/__*
    touch /var/lib/rpm/*
    rpm --rebuilddb
    rpm -qa
    yum -y install vim-minimal glibc-devel ncurses-static readline-static gcc gawk tar rsync procps patch bzip2
```

wrapper
```
#!/bin/sh
module --force purge
singularity exec -B/cvmfs /cvmfs/soft.computecanada.ca/custom/software/centos6.sif $1
```

and the patch to disable use of libcrypt and librt (Fedora 30 has renamed libcrypt.so.1 to .2 so it's not there anymore by default, may have garbled tabs):
```
--- lua-5.1.4.9.orig/luaposix/lposix.c  2017-01-20 20:24:52.000000000 +0000
+++ lua-5.1.4.9/luaposix/lposix.c       2020-05-05 23:44:29.603009847 +0000
@@ -1026,6 +1026,7 @@
 }
 #endif
 
+#if 0
 /*
  * XXX: GNU and BSD handle the forward declaration of crypt() in different
  * and annoying ways (especially GNU). Declare it here just to make sure
@@ -1048,6 +1049,7 @@
 
        return 1;
 }
+#endif
 
 /*     Like POSIX's setrlimit()/getrlimit() API functions.
  *
@@ -1208,7 +1210,8 @@
        return 1;
 }
 
-#ifndef DARWIN
+#if 0
+//#ifndef DARWIN
 static int get_clk_id_const(const char *str)
 {
           
@@ -1300,11 +1303,13 @@
        {"chdir",               Pchdir},
        {"chmod",               Pchmod},
        {"chown",               Pchown},
+#if 0
 #ifndef DARWIN
        {"clock_getres",        Pclock_getres},
        {"clock_gettime",       Pclock_gettime},
 #endif
        {"crypt",               Pcrypt},
+#endif
        {"ctermid",             Pctermid},
        {"dirname",             Pdirname},
        {"dir",                 Pdir},
diff -ur lua-5.1.4.9.orig/luaposix/Makefile lua-5.1.4.9/luaposix/Makefile
--- lua-5.1.4.9.orig/luaposix/Makefile  2017-01-20 20:24:52.000000000 +0000
+++ lua-5.1.4.9/luaposix/Makefile       2020-05-05 23:19:16.832248658 +0000
@@ -41,7 +41,8 @@
   LIBS=
 else
   LDFLAGS_SHARED=-shared
-  LIBS=-lcrypt -lrt
+  LIBS=
+  #-lcrypt -lrt
 endif
 
 # targets
```

**Comment by rjeschmi** [comment]
It looks good. I did a bit of tracing on my version just to be sure nothing is getting loaded weirdly and it all looks good other than those things you patched out. That is a good catch.

This is helpful and I suspect is why @mboisson mentioned it to me. Having a well defined bootstrap really helps getting into easybuild.

It feels like this could be tarballed up as a broader bootstrap for EB and maybe even be made relocatable.

Thanks for sharing.

**Comment by mboisson** [comment]
I would suggest adding the script(s) needed to this current repository. For a lack of a better place, at least it would be tracked and public.

**Comment by mboisson** [comment]
Pending the addition of the build script to this repository, this is probably ok to deploy next week.

**Comment by bartoldeman** [comment]
Pushed into prod now.

**Comment by mboisson** [comment]
@bartoldeman, Can you add the scripts to build lmod to git ? could be either this repository, or https://github.com/ComputeCanada/software-stack-custom this is where they are located on our node.

**Comment by bartoldeman** [comment]
ok
