### ISSUE TITLE
Potential SIGILL softwares in 2020 on Broadwell (AVX2) nodes

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#62]
Intel AVX2 using `xHost`
- [x] CheMPS2-1.8.9
- [x] BEEF-0.1.1
- [x] LAMMPS-20201029-20210319.170104
- [x] DALTON-2020

Intel/GCC AVX2 using `march=native` to verify
- [x] /avx2/Core/racon/1.4.13
- [x] /avx2/Core/rapidjson/1.1.0
- [x] /avx2/MPI/gcc9/openmpi4/hyphy/2.5.26
- [x] (false positive) /avx2/MPI/intel2020/openmpi4/openfoam-extend/4.1
- [x] /avx2/MPI/intel2020/openmpi4/dalton/2020
- [x] (false positive) /avx2/Compiler/gcc9/pov-ray/3.8.0-x.10064738
- [x] /avx2/Compiler/gcc9/iq-tree/2.0.7
- [x] /avx2/Compiler/gcc9/ntl/11.4.3
- [x] (false positive) /avx2/Compiler/gcc9/beagle-lib/3.1.2
- [x] /avx2/Compiler/intel2020/ntl/11.4.3
- [x] /avx2/Compiler/intel2020/iq-tree/2.0.7

When `-march=native` is the right most argument, it supersede the optarch argument given.

**Comment by mboisson** [comment]
I did `rapidjson`. `beagle-lib` does not seem to be an issue, as `-march=core-avx2` appears after `-march=native` in the command line

**Comment by alikerr** [comment]
Already got "illegal instructions" for LAMMPS and RACON ... I will fix these two modules first.

**Comment by mboisson** [comment]
RACON was fixed this morning.

**Comment by alikerr** [comment]
march=native and xHost fixed for lammps via a patch [https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/l/LAMMPS/lammps-20201029-fix-hardcoding.patch](url)

**Comment by mboisson** [comment]
Should be all fixed now.
