### ISSUE TITLE
CUDA nvprof fails because LD_LIBRARY_PATH does not point to CUDA libraries

### ISSUE THREAD

**Issue by ppomorsk** [ComputeCanada/software-stack#66]
nvprof does not work after CUDA module is loaded:

```
module load StdEnv/2020  cuda/11.0
nvcc test_cuda.cu
nvprof ./a.out 
======== Warning: The path to CUPTI and CUDA Injection libraries might not be set in LD_LIBRARY_PATH. By default, CUPTI library is installed in /usr/local/<cuda-toolkit>/extras/CUPTI/lib64 or /usr/local/<cuda-toolkit>/targets/<arch>/lib and CUDA Injection library is installed in /usr/local/<cuda-toolkit>/targets/<arch>/lib
======== Warning: No profile data collected.
```
Test code test_cuda.cu:

```c
#include <cuda.h>
int main(int argc, char *argv[]) {
    float *x_dev;   
    int n = 1024;
    size_t memsize;
    memsize = n * sizeof(float);
    cudaMalloc((void **) &x_dev, memsize);
    cudaFree(x_dev);
    return 0;
}
```

This can be fixed by defining 

```
export LD_LIBRARY_PATH=$EBROOTCUDA/lib64:$LD_LIBRARY_PATH
```

so this could be done by the CUDA module to fix the issue.

If defining LD_LIBRARY_PATH is not desirable, then hopefully another workaround can be found.

**Comment by ppomorsk** [comment]
I noticed that this issue does not arise if one uses nvcc and nvprof provided by the nvhpc/20.7 module (i.e. without loading the cuda module at all).

This might imply that we should encourage users to load nvhpc/20.7 instead of the cuda module, at least for code development.

**Comment by mboisson** [comment]
Also, this does not occur with cuda/11.1 or cuda/11.2.

**Comment by mboisson** [comment]
The one difference is: 
```$ find /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/ -name 'libaccinj64.so.11.0'
/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2/targets/x86_64-linux/lib/libaccinj64.so.11.0``` 

This is only present in CUDA 11.0.2.

**Comment by bartoldeman** [comment]
CUDA 11.1 fixed this in fact:
https://docs.nvidia.com/cuda/archive/11.1.0/cuda-toolkit-release-notes/index.html#cuda-tools-resolved-issues
-> "Fixed an issue that prevented profiling with nvprof without setting LD_LIBRARY_PATH to the lib64 folder. "

so the only way (and testing confirms this, RPATH has no influence, since it's the search path of the *compiled* executable, augmented by nvprof itself, in 11.1+, here that counts) to fix this is to create a wrapper script for nvprof, or tell users to set LD_LIBRARY_PATH or simply use 11.1 or later.
What do you think @mboisson

**Comment by mboisson** [comment]
So this is a CUDA bug... I guess a wrapper is the safest route. Fixing it for our default CUDA is rather important.

**Comment by mboisson** [comment]
I believe this change in the recipe will fix that: 

https://github.com/ComputeCanada/easybuild-easyconfigs/commit/08e9cb5e401899677e55bf6d12d615a73c1deb27

@bartoldeman, @ppomorsk thoughts ?

**Comment by mboisson** [comment]
This is now fixed in production.
