### ISSUE TITLE
Renaming `tensorflow_cpu` to `tensorflow` wheel

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#69]
The wheel for TF CPU is named `tensorflow`.
The wheel for TF GPU is named `tensorflow-gpu`.

The TF ecosystem wheels are looking for a `tensorflow` wheel which we do not have, we have `tensorflow_cpu`
To my knowledge and what I have seen so far, wheels depends on `tensorflow` and the user can install `tensorflow-gpu` wheel afterwards if desired.

Patching wheels to require `tensorflow_cpu` is unmaintenable. 
I suggest adding symbolic links for each wheels (v2.* and up) or renaming them to `tensorflow`. Symlinks will not disrupt any users workflows already using `tensorflow_cpu` and will future proof wheels added to the wheelhouse.

What was the premise to name the cpu wheel `tensorflow_cpu`?
Any potential issues renaming?

**Comment by ccoulombe** [comment]
@cmd-ntrf  @lemairecarl Any comments?

**Comment by mboisson** [comment]
Adding symlinks seem rather harmless to me.

**Comment by lemairecarl** [comment]
According to the docs, since TF > 1.15, there is only one package `tensorflow` which supports the GPU. I believe the `tensorflow-gpu` package is an alias. See also release notes: https://github.com/tensorflow/tensorflow/blob/298f7f146312b4943fbe1d439fceb4ecc1724dd1/RELEASE.md#major-features-and-improvements-5
It appears `tensorflow-cpu` is available, for those who want a smaller package.

**Comment by lemairecarl** [comment]
So are you suggesting that:
`tensorflow-cpu` should be named `tensorflow` in our wheelhouse, and that
`tensorflow` should be named `tensorflow-gpu` ?

I think it would be simpler to just provide `tensorflow` (which supports GPU), and have symlinks for `tensorflow-gpu` and `-cpu` which points to it.

**Comment by ccoulombe** [comment]
Indeed according to the docs :

> TensorFlow 2 packages are available 
> tensorflow —Latest stable release with CPU and GPU support (Ubuntu and Windows)
> tf-nightly —Preview build (unstable) . Ubuntu and Windows include GPU support .
> Older versions of TensorFlow 
> For TensorFlow 1.x, CPU and GPU packages are separate:
> 
> tensorflow==1.15 —Release for CPU-only
> tensorflow-gpu==1.15 —Release with GPU support (Ubuntu and Windows)

On PyPI both wheels (`tensorflow` and `tensorflow_gpu`) are built with GPU support since TF 2.1.

From now on, we should then only provide the `tensorflow` wheel for both CPU and GPU for TF 2.4.1 and upward
