### ISSUE TITLE
The mummer module depends on gnuplot

### ISSUE THREAD

**Issue by plstonge** [ComputeCanada/software-stack#78]
This comes from **Ticket#0132055**

With the `mummer/4.0.0beta2` module (with the `StdEnv/2020` environment), the `mummerplot` command is a script which is setting some `GNUPLOT_EXE` variable:
```
$ grep 'my $GNUPLOT_EXE' $(which mummerplot)
my $GNUPLOT_EXE = "false";
```
Consequently, `mummerplot` is trying to generate a plot with the `false` command, which will fail.

Under `StdEnv/2018.3`, the same `GNUPLOT_EXE` in `mummer/4.0.0beta2` module has a direct path to the Nix global `gnuplot` command. Since `gnuplot` is now a "scientific" module in `StdEnv/2020`, it should probably be a dependency of `mummer`. Otherwise, the `mummerplot` command would have to have a proper path to the `gnuplot` executable.

Thank you.

**Comment by mboisson** [comment]
fixed with
