### ISSUE TITLE
Unbreaking `pip>=21`: add a "computecanada" local version to wheels provided by Compute Canada

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#80]
Our current setup with Python relies on having our wheelhouse take precedence over packages hosted on PyPI. This is something that `pip` developers insist on not supporting (https://github.com/pypa/pip/issues/8606). They insist that all indexes are to be considered equivalent and allow no prioritization between them. 

This is actually broken starting with pip>=21. For the time being, we have put a constraint on `pip < 21` so that our users don't end up with a broken setup. 

Possible solutions
1) Stay with pip<21 forever. This is not really a good option for obvious reasons
2) Contribute to pip to add a feature to prioritize indexes. This is unlikely to be accepted. Many such attempts have been shut down by pip developers. 
3) Run a devpi server (https://github.com/devpi/devpi) which would forward to PyPI only those packages we don't provide. This is the solution the developers suggest. This however requires running a server, with appropriate production-level uptime. This is not an easy task
4) Patch and maintain a patch for pip. It is unclear how maintainable this is in the long time. 

This issue is to discuss what amount of work and maintenance this would require.

**Comment by cmd-ntrf** [comment]
There is a fifth option: use conda.
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

**Comment by pradyunsg** [comment]
> * Run a devpi server (https://github.com/devpi/devpi) which would forward to PyPI only those packages we don't provide. This is the solution the developers suggest. This however requires running a server, with appropriate production-level uptime. This is not an easy task

If you're whipping up a server, something like https://github.com/uranusjr/simpleindex might be easier to use than devpi.

**Comment by mboisson** [comment]
> > * Run a devpi server (https://github.com/devpi/devpi) which would forward to PyPI only those packages we don't provide. This is the solution the developers suggest. This however requires running a server, with appropriate production-level uptime. This is not an easy task
> 
> If you're whipping up a server, something like https://github.com/uranusjr/simpleindex might be easier to use than devpi.

Thanks. The page points to using `pipx` however. We are very much trying to not stray away from `pip` because that involves tons of user re-training (we have thousands of users).

**Comment by pradyunsg** [comment]
pipx is a helper that creates an isolated environment for the command line interface of that application.

Basically, it creates a virtualenv, installs the said package and puts a generated script on PATH to run the script from within that virtualenv. In terms of a series of CLI commands, you can equivalently do:

```
$ python -m /home/user/.local/pipx/venvs/simpleindex .venv
$ source /home/user/.local/pipx/venvs/simpleindex/bin/activate
$ pip install simpleindex
```

Other than adding a `simpleindex` script to the user's PATH that makes it much easier to run, pipx is roughly equivalent to the above.

**Comment by pradyunsg** [comment]
> The page points to using `pipx` however.

I've gone ahead and filed https://github.com/uranusjr/simpleindex/issues/3, since you seem to have been confused by the fact that the README only mentions pipx; and assumed that the package isn't usable with pip. :)

**Comment by mboisson** [comment]
Ah, so `pipx` is just to install the `simpleindex` server, (which we can do differently through a virtualenv or any other python isolation method we prefer). 

Users would still call `pip install ...`   (and our `PIP_CONFIG_FILE` would point to the server as an index).

**Comment by pradyunsg** [comment]
Yep.

**Comment by pradyunsg** [comment]
FWIW, if you do want to have an chat about this whole thing, I'd be happy to chat for a bit [over the weekend](https://calendly.com/pradyunsg/weekend-time).

**Comment by mboisson** [comment]
I wonder what the impacts would be to use a wrapper script around `pip`, which would launch a server locally and shut it down after 🤔

**Comment by pradyunsg** [comment]
There's some follow up discussion at https://github.com/pypa/pip/issues/10156.

**Comment by mboisson** [comment]
Option 6) Rename our wheels from `<name>-<version>-<other qualifiers>.whl`  to `<name>-<version>-1computecanada-<other qualifiers>.whl`   (use build tags): https://packaging.python.org/specifications/binary-distribution-format/#file-name-convention
Option 7) Build our wheels using a local version identifier which would yield `<name>-<version>+computecanada-<other qualifiers>.whl`: https://www.python.org/dev/peps/pep-0440/#local-version-identifiers

Options 6 and 7 were pointed out by @pradyunsg in issue pypa/pip#10156

Option 7 requires editing `setup.py` with something like this: 
```
sed -i -e "s/version=\([^,]*\),/version=\1+\"+computecanada\",/g" setup.py
``` 
This is potentially brittle, but editing `setup.py` is something we already do, in particular to fix packages which use `distutils.core` rather than `setuptools` for their `setup` function. 


I tested with `pyzmq`, with local wheels and pypi, with pip 21, if we don't disable `manylinux` compatibility. 
With: `pip install pyzmq==21.0.1 --find-links $WHEELHOUSE`, the order of preference seems to be: 
1) `pyzmq-21.0.1+computecanada-cp38-cp38-linux_x86_64.whl`                     (option 7)
2) `pyzmq-21.0.1-1computecanada-cp38-cp38-manylinux2010_x86_64.whl` (option 6, but manylinux2010)
3) `pyzmq-21.0.1-cp38-cp38-manylinux2010_x86_64.whl`                                (from pypi)
4) `pyzmq-21.0.1-1computecanada-cp38-cp38-linux_x86_64.whl`                   (option 6)
5) `pyzmq-21.0.1-cp38-cp38-linux_x86_64.whl`                                                  (current state)
6) `pyzmq-21.0.1.tar.gz`                                                                                            (building from source from pypi)

If we disable `manylinux` compatibility, then it becomes
1) `pyzmq-21.0.1+computecanada-cp38-cp38-linux_x86_64.whl`                     (option 7)
2) `pyzmq-21.0.1-1computecanada-cp38-cp38-linux_x86_64.whl`                   (option 6)
3) `pyzmq-21.0.1-cp38-cp38-linux_x86_64.whl`                                                  (current state)
4) `pyzmq-21.0.1.tar.gz`                                                                                            (building from source from pypi)

With `pip install pyzmq --find-links $WHEELHOUSE`, then it downloads the latest version (currently `22.1.0`) from pypi. 

Option 7 has the additional effect that `pip freeze` or `pip list` will now report that version `21.0.1+computecanada` is installed, while option 6 will show `21.0.1`. 

Option 7 has the additional benefit that it takes precedence over `manylinux` wheels (but this has no impact if we disable `manylinux` support anyway). 

In the case of option 6, we can just create symlinks with the extra build tag. In case of option 7, this has to be changed at build time. For existing wheels, option 6 with symlinks seems like an easy solution. For future wheels, option 7 seems like a better solution because of the added benefit of showing in the output of `pip freeze`, which can be useful for debugging.

**Comment by pradyunsg** [comment]
> Option 7 requires editing setup.py with something like this:

This is super fragile. Packages are permitted to use specify their versions in many ways in setup.py (eg: see pip's setup.py, setuptools_scm) or use a completely different build tool (eg: poetry,flit etc) which don't even use setuptools.

I'd suggest instead modifying the generated wheel if you want to go down this route.

**Comment by mboisson** [comment]
> > Option 7 requires editing setup.py with something like this:
> 
> This is super fragile. Packages are permitted to use specify their versions in many ways in setup.py (eg: see pip's setup.py, setuptools_scm) or use a completely different build tool (eg: poetry,flit etc) which don't even use setuptools.
> 
> I'd suggest instead modifying the generated wheel if you want to go down this route.

This looks more involved, from what I can see, this would require: 
1) Unzipping the wheel
2) Rename the `<name>-<version>.dist-info` folder into `<name>-<version>+computecanada.dist-info` 
3) `sed` the new version into `<name>-<version>+computecanada.dist-info/METADATA`
4) Compute a new `sha256` for the updated `<name>-<version>+computecanada.dist-info/METADATA` file
5) update `<name>-<version>+computecanada.dist-info/RECORD` :
5.1) replace all `<name>-<version>.dist-info` by `<name>-<version>+computecanada.dist-info` in it
5.2) update the `sha256` for the `METADATA` file
6) Zip the wheel back
7) Rename the wheel to include the `+computecanada` 

Is that correct ?

**Comment by pradyunsg** [comment]
https://github.com/MrMino/wheelfile -- this should make things a lot simpler, although, I must admit, I don't know how well that handles rewriting the RECORD file / moving the dost-info folder. It might be worth poking the author there about this though. They're usually pretty active. :)

**Comment by mboisson** [comment]
As of July 22nd 2021, all wheels have been patched to display the local version "computecanada". Some of them have yet to be deployed.

**Comment by mboisson** [comment]
This is now completed.
