### ISSUE TITLE
Define SCREENDIR

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#9]
Currently, `SCREENDIR` is unset, and `screen` creates `/tmp/uscreens/` through the first user uses `screen` on the node. 

This means that the first user could rename other users' screen folder. 

Proposal, in our default modules

1. if `/tmp/uscreens/S-$USER` exists and is not empty, define `SCREENDIR=/tmp/uscreens/S-$USER` 
2. else, define `SCREENDIR=/tmp/S-$USER` 

This will both ensure continuity for existing session, and fix the issues for future sessions.

**Comment by bartoldeman** [comment]
here's my solution:
compile both Nix and Gentoo screen using `--with-socket-dir=/tmp`.

Use a wrapper script in `/cvmfs/soft.computecanada.ca/custom/bin/screen` as follows:
```
#!/bin/bash

# https://unix.stackexchange.com/questions/202243/how-to-check-directory-is-empty
function emptydir {   
 [ "$(shopt -s nullglob; echo "$1"/{,.[^.],..?}*)" = "" ]
}

if [ -z "$SCREENDIR" ]; then
        NIX_SCREENDIR=/tmp/uscreens/S-$USER
        if [[ -d $NIX_SCREENDIR ]]; then
                if ! emptydir $NIX_SCREENDIR; then
                        export SCREENDIR=$NIX_SCREENDIR
                fi
        fi
fi
${EBROOTGENTOO-NIXUSER_PROFILE}/bin/screen ${1+"$@"}
```
This will take care of setting SCREENDIR if S-$USER files are still present.
It's on build-node only now.

**Comment by mboisson** [comment]
I think this is ok to deploy next week.

**Comment by bartoldeman** [comment]
Deployed now.
