### ISSUE TITLE
Get XALT working on clusters

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#90]
The EasyConfig XALT recipe is here: 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-main/easybuild/easyconfigs/x/XALT/XALT-2.10.15.eb

More documentation produced by @JLague is available here: 
https://github.com/JLague/xalt_doc

We need to work with the systems team to accumulate the logs and collect them in ES.

**Comment by ccoulombe** [comment]
The xalt documentation should be moved to the CC GH organization, and any reference to it should be updated accordingly.

**Comment by JLague** [comment]
The xalt documentation has been moved to the CC GH organization under the RSNT-Software-Maintainers team:
https://github.com/ComputeCanada/xalt_doc
