### ISSUE TITLE
Automate the deployment of our build infrastructure

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/software-stack#98]
A few reasons to do this
1) allow us to more easily provision extra build nodes as time requires
2) document our configuration better
3) ensure nodes are coherent

**Comment by mboisson** [comment]
@vollmerk

**Comment by vollmerk** [comment]
Configuration data is being stored at https://git.computecanada.ca/cc-provisioning-hiera/rsnt I'm currently running through reverse engineering the configuration, and trying to validate things that might be historical and no longer valid

**Comment by mboisson** [comment]
This is now completed using Magic Castle.
