### ISSUE TITLE
Getting Rstudio-server functionnal accross the different sites

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/software-stack#99]
- [x] Installing Rstudio-server 
- [x] jupyter-lmod to support `+` in names (fixed in https://github.com/cmd-ntrf/jupyter-lmod/commit/b12dd8a2f9ed918352b574ac8a6b46c7ba8dc987)
- [x]  Remove command `rserver` from [pupper-jupyterhub](https://github.com/ComputeCanada/puppet-jupyterhub/blob/main/data/common.yaml#L42)
- [x] Update [puppet-jupyterhub](https://github.com/ComputeCanada/puppet-jupyterhub/blob/main/manifests/node.pp#L66) to use  [jupyter-rstudio-proxy](https://github.com/ComputeCanada/jupyter-rsession-proxy/tree/rstudio-server)
- [x] Add logic for StdEnv/2018 v1.2 vs StdEnv/2020 v2021 to use `--server-data-dir` or not
- [x] Add patched wheel for `jupyter-rsession-proxy` ?
- [ ] Update sites to use the above (update site puppet-jupyterhub)

**Comment by ccoulombe** [comment]
`puppet-jupyterhub` is updated in https://github.com/ComputeCanada/puppet-jupyterhub/pull/26

**Comment by mboisson** [comment]
Can you document what exactly must be done to "Update sites" ?

**Comment by cmd-ntrf** [comment]
Steps to deploy the puppet-jupyterhub node class on CVMFS is documented here:
https://github.com/ComputeCanada/puppet-jupyterhub/wiki/Installing-jupyterhub::node-on-CVMFS

I have deployed v4.1.0 on CVMFS.

Sites now have to update their hub to use puppet-jupyterhub v4.1.0. This requires
- Updating puppet-jupyterhub ref in Puppetfile to v4.1.0
- removing `/opt/jupyterhub` from the hub
- removing `/run/jupyterhub` from the hub
- Apply puppet plan for the hub.

**Comment by mboisson** [comment]
This now works on Narval, Béluga and Cedar. Since Graham's JupyterHub is not in production as far as I know, I am closing this.
